// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/authzevent"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/predicate"
)

// AuthzEventDelete is the builder for deleting a AuthzEvent entity.
type AuthzEventDelete struct {
	config
	hooks    []Hook
	mutation *AuthzEventMutation
}

// Where appends a list predicates to the AuthzEventDelete builder.
func (_d *AuthzEventDelete) Where(ps ...predicate.AuthzEvent) *AuthzEventDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AuthzEventDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AuthzEventDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AuthzEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(authzevent.Table, sqlgraph.NewFieldSpec(authzevent.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AuthzEventDeleteOne is the builder for deleting a single AuthzEvent entity.
type AuthzEventDeleteOne struct {
	_d *AuthzEventDelete
}

// Where appends a list predicates to the AuthzEventDelete builder.
func (_d *AuthzEventDeleteOne) Where(ps ...predicate.AuthzEvent) *AuthzEventDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AuthzEventDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{authzevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AuthzEventDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
