// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/device"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/predicate"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/twofactorchallenge"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/user"
)

// DeviceUpdate is the builder for updating Device entities.
type DeviceUpdate struct {
	config
	hooks     []Hook
	mutation  *DeviceMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the DeviceUpdate builder.
func (_u *DeviceUpdate) Where(ps ...predicate.Device) *DeviceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DeviceUpdate) SetUpdatedAt(v time.Time) *DeviceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *DeviceUpdate) ClearUpdatedAt() *DeviceUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *DeviceUpdate) SetUserID(v uuid.UUID) *DeviceUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableUserID(v *uuid.UUID) *DeviceUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetFingerprint sets the "fingerprint" field.
func (_u *DeviceUpdate) SetFingerprint(v string) *DeviceUpdate {
	_u.mutation.SetFingerprint(v)
	return _u
}

// SetNillableFingerprint sets the "fingerprint" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableFingerprint(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetFingerprint(*v)
	}
	return _u
}

// SetLabel sets the "label" field.
func (_u *DeviceUpdate) SetLabel(v string) *DeviceUpdate {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableLabel(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// ClearLabel clears the value of the "label" field.
func (_u *DeviceUpdate) ClearLabel() *DeviceUpdate {
	_u.mutation.ClearLabel()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *DeviceUpdate) SetUserAgent(v string) *DeviceUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableUserAgent(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *DeviceUpdate) ClearUserAgent() *DeviceUpdate {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *DeviceUpdate) SetLastSeenAt(v time.Time) *DeviceUpdate {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableLastSeenAt(v *time.Time) *DeviceUpdate {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (_u *DeviceUpdate) ClearLastSeenAt() *DeviceUpdate {
	_u.mutation.ClearLastSeenAt()
	return _u
}

// SetLastIP sets the "last_ip" field.
func (_u *DeviceUpdate) SetLastIP(v string) *DeviceUpdate {
	_u.mutation.SetLastIP(v)
	return _u
}

// SetNillableLastIP sets the "last_ip" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableLastIP(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetLastIP(*v)
	}
	return _u
}

// ClearLastIP clears the value of the "last_ip" field.
func (_u *DeviceUpdate) ClearLastIP() *DeviceUpdate {
	_u.mutation.ClearLastIP()
	return _u
}

// SetTrustedAt sets the "trusted_at" field.
func (_u *DeviceUpdate) SetTrustedAt(v time.Time) *DeviceUpdate {
	_u.mutation.SetTrustedAt(v)
	return _u
}

// SetNillableTrustedAt sets the "trusted_at" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableTrustedAt(v *time.Time) *DeviceUpdate {
	if v != nil {
		_u.SetTrustedAt(*v)
	}
	return _u
}

// ClearTrustedAt clears the value of the "trusted_at" field.
func (_u *DeviceUpdate) ClearTrustedAt() *DeviceUpdate {
	_u.mutation.ClearTrustedAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *DeviceUpdate) SetRevokedAt(v time.Time) *DeviceUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableRevokedAt(v *time.Time) *DeviceUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *DeviceUpdate) ClearRevokedAt() *DeviceUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *DeviceUpdate) SetUser(v *User) *DeviceUpdate {
	return _u.SetUserID(v.ID)
}

// AddChallengeIDs adds the "challenges" edge to the TwoFactorChallenge entity by IDs.
func (_u *DeviceUpdate) AddChallengeIDs(ids ...uuid.UUID) *DeviceUpdate {
	_u.mutation.AddChallengeIDs(ids...)
	return _u
}

// AddChallenges adds the "challenges" edges to the TwoFactorChallenge entity.
func (_u *DeviceUpdate) AddChallenges(v ...*TwoFactorChallenge) *DeviceUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChallengeIDs(ids...)
}

// Mutation returns the DeviceMutation object of the builder.
func (_u *DeviceUpdate) Mutation() *DeviceMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *DeviceUpdate) ClearUser() *DeviceUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearChallenges clears all "challenges" edges to the TwoFactorChallenge entity.
func (_u *DeviceUpdate) ClearChallenges() *DeviceUpdate {
	_u.mutation.ClearChallenges()
	return _u
}

// RemoveChallengeIDs removes the "challenges" edge to TwoFactorChallenge entities by IDs.
func (_u *DeviceUpdate) RemoveChallengeIDs(ids ...uuid.UUID) *DeviceUpdate {
	_u.mutation.RemoveChallengeIDs(ids...)
	return _u
}

// RemoveChallenges removes "challenges" edges to TwoFactorChallenge entities.
func (_u *DeviceUpdate) RemoveChallenges(v ...*TwoFactorChallenge) *DeviceUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChallengeIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DeviceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeviceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DeviceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeviceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DeviceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := device.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeviceUpdate) check() error {
	if v, ok := _u.mutation.Fingerprint(); ok {
		if err := device.FingerprintValidator(v); err != nil {
			return &ValidationError{Name: "fingerprint", err: fmt.Errorf(`ent: validator failed for field "Device.fingerprint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Label(); ok {
		if err := device.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "Device.label": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := device.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "Device.user_agent": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Device.user"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DeviceUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DeviceUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DeviceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(device.Table, device.Columns, sqlgraph.NewFieldSpec(device.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(device.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(device.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(device.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Fingerprint(); ok {
		_spec.SetField(device.FieldFingerprint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(device.FieldLabel, field.TypeString, value)
	}
	if _u.mutation.LabelCleared() {
		_spec.ClearField(device.FieldLabel, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(device.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(device.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(device.FieldLastSeenAt, field.TypeTime, value)
	}
	if _u.mutation.LastSeenAtCleared() {
		_spec.ClearField(device.FieldLastSeenAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastIP(); ok {
		_spec.SetField(device.FieldLastIP, field.TypeString, value)
	}
	if _u.mutation.LastIPCleared() {
		_spec.ClearField(device.FieldLastIP, field.TypeString)
	}
	if value, ok := _u.mutation.TrustedAt(); ok {
		_spec.SetField(device.FieldTrustedAt, field.TypeTime, value)
	}
	if _u.mutation.TrustedAtCleared() {
		_spec.ClearField(device.FieldTrustedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(device.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(device.FieldRevokedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.UserTable,
			Columns: []string{device.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.UserTable,
			Columns: []string{device.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChallengesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   device.ChallengesTable,
			Columns: []string{device.ChallengesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(twofactorchallenge.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChallengesIDs(); len(nodes) > 0 && !_u.mutation.ChallengesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   device.ChallengesTable,
			Columns: []string{device.ChallengesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(twofactorchallenge.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChallengesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   device.ChallengesTable,
			Columns: []string{device.ChallengesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(twofactorchallenge.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{device.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DeviceUpdateOne is the builder for updating a single Device entity.
type DeviceUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *DeviceMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DeviceUpdateOne) SetUpdatedAt(v time.Time) *DeviceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *DeviceUpdateOne) ClearUpdatedAt() *DeviceUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *DeviceUpdateOne) SetUserID(v uuid.UUID) *DeviceUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableUserID(v *uuid.UUID) *DeviceUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetFingerprint sets the "fingerprint" field.
func (_u *DeviceUpdateOne) SetFingerprint(v string) *DeviceUpdateOne {
	_u.mutation.SetFingerprint(v)
	return _u
}

// SetNillableFingerprint sets the "fingerprint" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableFingerprint(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetFingerprint(*v)
	}
	return _u
}

// SetLabel sets the "label" field.
func (_u *DeviceUpdateOne) SetLabel(v string) *DeviceUpdateOne {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableLabel(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// ClearLabel clears the value of the "label" field.
func (_u *DeviceUpdateOne) ClearLabel() *DeviceUpdateOne {
	_u.mutation.ClearLabel()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *DeviceUpdateOne) SetUserAgent(v string) *DeviceUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableUserAgent(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *DeviceUpdateOne) ClearUserAgent() *DeviceUpdateOne {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *DeviceUpdateOne) SetLastSeenAt(v time.Time) *DeviceUpdateOne {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableLastSeenAt(v *time.Time) *DeviceUpdateOne {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (_u *DeviceUpdateOne) ClearLastSeenAt() *DeviceUpdateOne {
	_u.mutation.ClearLastSeenAt()
	return _u
}

// SetLastIP sets the "last_ip" field.
func (_u *DeviceUpdateOne) SetLastIP(v string) *DeviceUpdateOne {
	_u.mutation.SetLastIP(v)
	return _u
}

// SetNillableLastIP sets the "last_ip" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableLastIP(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetLastIP(*v)
	}
	return _u
}

// ClearLastIP clears the value of the "last_ip" field.
func (_u *DeviceUpdateOne) ClearLastIP() *DeviceUpdateOne {
	_u.mutation.ClearLastIP()
	return _u
}

// SetTrustedAt sets the "trusted_at" field.
func (_u *DeviceUpdateOne) SetTrustedAt(v time.Time) *DeviceUpdateOne {
	_u.mutation.SetTrustedAt(v)
	return _u
}

// SetNillableTrustedAt sets the "trusted_at" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableTrustedAt(v *time.Time) *DeviceUpdateOne {
	if v != nil {
		_u.SetTrustedAt(*v)
	}
	return _u
}

// ClearTrustedAt clears the value of the "trusted_at" field.
func (_u *DeviceUpdateOne) ClearTrustedAt() *DeviceUpdateOne {
	_u.mutation.ClearTrustedAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *DeviceUpdateOne) SetRevokedAt(v time.Time) *DeviceUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableRevokedAt(v *time.Time) *DeviceUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *DeviceUpdateOne) ClearRevokedAt() *DeviceUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *DeviceUpdateOne) SetUser(v *User) *DeviceUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddChallengeIDs adds the "challenges" edge to the TwoFactorChallenge entity by IDs.
func (_u *DeviceUpdateOne) AddChallengeIDs(ids ...uuid.UUID) *DeviceUpdateOne {
	_u.mutation.AddChallengeIDs(ids...)
	return _u
}

// AddChallenges adds the "challenges" edges to the TwoFactorChallenge entity.
func (_u *DeviceUpdateOne) AddChallenges(v ...*TwoFactorChallenge) *DeviceUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChallengeIDs(ids...)
}

// Mutation returns the DeviceMutation object of the builder.
func (_u *DeviceUpdateOne) Mutation() *DeviceMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *DeviceUpdateOne) ClearUser() *DeviceUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearChallenges clears all "challenges" edges to the TwoFactorChallenge entity.
func (_u *DeviceUpdateOne) ClearChallenges() *DeviceUpdateOne {
	_u.mutation.ClearChallenges()
	return _u
}

// RemoveChallengeIDs removes the "challenges" edge to TwoFactorChallenge entities by IDs.
func (_u *DeviceUpdateOne) RemoveChallengeIDs(ids ...uuid.UUID) *DeviceUpdateOne {
	_u.mutation.RemoveChallengeIDs(ids...)
	return _u
}

// RemoveChallenges removes "challenges" edges to TwoFactorChallenge entities.
func (_u *DeviceUpdateOne) RemoveChallenges(v ...*TwoFactorChallenge) *DeviceUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChallengeIDs(ids...)
}

// Where appends a list predicates to the DeviceUpdate builder.
func (_u *DeviceUpdateOne) Where(ps ...predicate.Device) *DeviceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DeviceUpdateOne) Select(field string, fields ...string) *DeviceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Device entity.
func (_u *DeviceUpdateOne) Save(ctx context.Context) (*Device, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeviceUpdateOne) SaveX(ctx context.Context) *Device {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DeviceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeviceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DeviceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := device.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeviceUpdateOne) check() error {
	if v, ok := _u.mutation.Fingerprint(); ok {
		if err := device.FingerprintValidator(v); err != nil {
			return &ValidationError{Name: "fingerprint", err: fmt.Errorf(`ent: validator failed for field "Device.fingerprint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Label(); ok {
		if err := device.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "Device.label": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := device.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "Device.user_agent": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Device.user"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DeviceUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DeviceUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DeviceUpdateOne) sqlSave(ctx context.Context) (_node *Device, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(device.Table, device.Columns, sqlgraph.NewFieldSpec(device.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Device.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, device.FieldID)
		for _, f := range fields {
			if !device.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != device.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(device.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(device.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(device.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Fingerprint(); ok {
		_spec.SetField(device.FieldFingerprint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(device.FieldLabel, field.TypeString, value)
	}
	if _u.mutation.LabelCleared() {
		_spec.ClearField(device.FieldLabel, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(device.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(device.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(device.FieldLastSeenAt, field.TypeTime, value)
	}
	if _u.mutation.LastSeenAtCleared() {
		_spec.ClearField(device.FieldLastSeenAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastIP(); ok {
		_spec.SetField(device.FieldLastIP, field.TypeString, value)
	}
	if _u.mutation.LastIPCleared() {
		_spec.ClearField(device.FieldLastIP, field.TypeString)
	}
	if value, ok := _u.mutation.TrustedAt(); ok {
		_spec.SetField(device.FieldTrustedAt, field.TypeTime, value)
	}
	if _u.mutation.TrustedAtCleared() {
		_spec.ClearField(device.FieldTrustedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(device.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(device.FieldRevokedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.UserTable,
			Columns: []string{device.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.UserTable,
			Columns: []string{device.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChallengesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   device.ChallengesTable,
			Columns: []string{device.ChallengesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(twofactorchallenge.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChallengesIDs(); len(nodes) > 0 && !_u.mutation.ChallengesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   device.ChallengesTable,
			Columns: []string{device.ChallengesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(twofactorchallenge.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChallengesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   device.ChallengesTable,
			Columns: []string{device.ChallengesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(twofactorchallenge.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Device{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{device.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
