// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/emailchange"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/user"
)

// EmailChangeCreate is the builder for creating a EmailChange entity.
type EmailChangeCreate struct {
	config
	mutation *EmailChangeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *EmailChangeCreate) SetCreatedAt(v time.Time) *EmailChangeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EmailChangeCreate) SetNillableCreatedAt(v *time.Time) *EmailChangeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EmailChangeCreate) SetUpdatedAt(v time.Time) *EmailChangeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EmailChangeCreate) SetNillableUpdatedAt(v *time.Time) *EmailChangeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *EmailChangeCreate) SetUserID(v uuid.UUID) *EmailChangeCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNewEmail sets the "new_email" field.
func (_c *EmailChangeCreate) SetNewEmail(v string) *EmailChangeCreate {
	_c.mutation.SetNewEmail(v)
	return _c
}

// SetCodeHash sets the "code_hash" field.
func (_c *EmailChangeCreate) SetCodeHash(v string) *EmailChangeCreate {
	_c.mutation.SetCodeHash(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *EmailChangeCreate) SetExpiresAt(v time.Time) *EmailChangeCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetAttempts sets the "attempts" field.
func (_c *EmailChangeCreate) SetAttempts(v int) *EmailChangeCreate {
	_c.mutation.SetAttempts(v)
	return _c
}

// SetConsumedAt sets the "consumed_at" field.
func (_c *EmailChangeCreate) SetConsumedAt(v time.Time) *EmailChangeCreate {
	_c.mutation.SetConsumedAt(v)
	return _c
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_c *EmailChangeCreate) SetNillableConsumedAt(v *time.Time) *EmailChangeCreate {
	if v != nil {
		_c.SetConsumedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *EmailChangeCreate) SetID(v uuid.UUID) *EmailChangeCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *EmailChangeCreate) SetNillableID(v *uuid.UUID) *EmailChangeCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *EmailChangeCreate) SetUser(v *User) *EmailChangeCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the EmailChangeMutation object of the builder.
func (_c *EmailChangeCreate) Mutation() *EmailChangeMutation {
	return _c.mutation
}

// Save creates the EmailChange in the database.
func (_c *EmailChangeCreate) Save(ctx context.Context) (*EmailChange, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EmailChangeCreate) SaveX(ctx context.Context) *EmailChange {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EmailChangeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EmailChangeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EmailChangeCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := emailchange.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := emailchange.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := emailchange.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EmailChangeCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "EmailChange.user_id"`)}
	}
	if _, ok := _c.mutation.NewEmail(); !ok {
		return &ValidationError{Name: "new_email", err: errors.New(`ent: missing required field "EmailChange.new_email"`)}
	}
	if v, ok := _c.mutation.NewEmail(); ok {
		if err := emailchange.NewEmailValidator(v); err != nil {
			return &ValidationError{Name: "new_email", err: fmt.Errorf(`ent: validator failed for field "EmailChange.new_email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CodeHash(); !ok {
		return &ValidationError{Name: "code_hash", err: errors.New(`ent: missing required field "EmailChange.code_hash"`)}
	}
	if v, ok := _c.mutation.CodeHash(); ok {
		if err := emailchange.CodeHashValidator(v); err != nil {
			return &ValidationError{Name: "code_hash", err: fmt.Errorf(`ent: validator failed for field "EmailChange.code_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "EmailChange.expires_at"`)}
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		return &ValidationError{Name: "attempts", err: errors.New(`ent: missing required field "EmailChange.attempts"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "EmailChange.user"`)}
	}
	return nil
}

func (_c *EmailChangeCreate) sqlSave(ctx context.Context) (*EmailChange, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EmailChangeCreate) createSpec() (*EmailChange, *sqlgraph.CreateSpec) {
	var (
		_node = &EmailChange{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(emailchange.Table, sqlgraph.NewFieldSpec(emailchange.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(emailchange.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(emailchange.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.NewEmail(); ok {
		_spec.SetField(emailchange.FieldNewEmail, field.TypeString, value)
		_node.NewEmail = value
	}
	if value, ok := _c.mutation.CodeHash(); ok {
		_spec.SetField(emailchange.FieldCodeHash, field.TypeString, value)
		_node.CodeHash = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(emailchange.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.Attempts(); ok {
		_spec.SetField(emailchange.FieldAttempts, field.TypeInt, value)
		_node.Attempts = value
	}
	if value, ok := _c.mutation.ConsumedAt(); ok {
		_spec.SetField(emailchange.FieldConsumedAt, field.TypeTime, value)
		_node.ConsumedAt = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   emailchange.UserTable,
			Columns: []string{emailchange.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EmailChange.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EmailChangeUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *EmailChangeCreate) OnConflict(opts ...sql.ConflictOption) *EmailChangeUpsertOne {
	_c.conflict = opts
	return &EmailChangeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EmailChange.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EmailChangeCreate) OnConflictColumns(columns ...string) *EmailChangeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EmailChangeUpsertOne{
		create: _c,
	}
}

type (
	// EmailChangeUpsertOne is the builder for "upsert"-ing
	//  one EmailChange node.
	EmailChangeUpsertOne struct {
		create *EmailChangeCreate
	}

	// EmailChangeUpsert is the "OnConflict" setter.
	EmailChangeUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *EmailChangeUpsert) SetUpdatedAt(v time.Time) *EmailChangeUpsert {
	u.Set(emailchange.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EmailChangeUpsert) UpdateUpdatedAt() *EmailChangeUpsert {
	u.SetExcluded(emailchange.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *EmailChangeUpsert) ClearUpdatedAt() *EmailChangeUpsert {
	u.SetNull(emailchange.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *EmailChangeUpsert) SetUserID(v uuid.UUID) *EmailChangeUpsert {
	u.Set(emailchange.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *EmailChangeUpsert) UpdateUserID() *EmailChangeUpsert {
	u.SetExcluded(emailchange.FieldUserID)
	return u
}

// SetNewEmail sets the "new_email" field.
func (u *EmailChangeUpsert) SetNewEmail(v string) *EmailChangeUpsert {
	u.Set(emailchange.FieldNewEmail, v)
	return u
}

// UpdateNewEmail sets the "new_email" field to the value that was provided on create.
func (u *EmailChangeUpsert) UpdateNewEmail() *EmailChangeUpsert {
	u.SetExcluded(emailchange.FieldNewEmail)
	return u
}

// SetCodeHash sets the "code_hash" field.
func (u *EmailChangeUpsert) SetCodeHash(v string) *EmailChangeUpsert {
	u.Set(emailchange.FieldCodeHash, v)
	return u
}

// UpdateCodeHash sets the "code_hash" field to the value that was provided on create.
func (u *EmailChangeUpsert) UpdateCodeHash() *EmailChangeUpsert {
	u.SetExcluded(emailchange.FieldCodeHash)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *EmailChangeUpsert) SetExpiresAt(v time.Time) *EmailChangeUpsert {
	u.Set(emailchange.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *EmailChangeUpsert) UpdateExpiresAt() *EmailChangeUpsert {
	u.SetExcluded(emailchange.FieldExpiresAt)
	return u
}

// SetAttempts sets the "attempts" field.
func (u *EmailChangeUpsert) SetAttempts(v int) *EmailChangeUpsert {
	u.Set(emailchange.FieldAttempts, v)
	return u
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *EmailChangeUpsert) UpdateAttempts() *EmailChangeUpsert {
	u.SetExcluded(emailchange.FieldAttempts)
	return u
}

// AddAttempts adds v to the "attempts" field.
func (u *EmailChangeUpsert) AddAttempts(v int) *EmailChangeUpsert {
	u.Add(emailchange.FieldAttempts, v)
	return u
}

// SetConsumedAt sets the "consumed_at" field.
func (u *EmailChangeUpsert) SetConsumedAt(v time.Time) *EmailChangeUpsert {
	u.Set(emailchange.FieldConsumedAt, v)
	return u
}

// UpdateConsumedAt sets the "consumed_at" field to the value that was provided on create.
func (u *EmailChangeUpsert) UpdateConsumedAt() *EmailChangeUpsert {
	u.SetExcluded(emailchange.FieldConsumedAt)
	return u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (u *EmailChangeUpsert) ClearConsumedAt() *EmailChangeUpsert {
	u.SetNull(emailchange.FieldConsumedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.EmailChange.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(emailchange.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *EmailChangeUpsertOne) UpdateNewValues() *EmailChangeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(emailchange.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(emailchange.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EmailChange.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EmailChangeUpsertOne) Ignore() *EmailChangeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EmailChangeUpsertOne) DoNothing() *EmailChangeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EmailChangeCreate.OnConflict
// documentation for more info.
func (u *EmailChangeUpsertOne) Update(set func(*EmailChangeUpsert)) *EmailChangeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EmailChangeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EmailChangeUpsertOne) SetUpdatedAt(v time.Time) *EmailChangeUpsertOne {
	return u.Update(func(s *EmailChangeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EmailChangeUpsertOne) UpdateUpdatedAt() *EmailChangeUpsertOne {
	return u.Update(func(s *EmailChangeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *EmailChangeUpsertOne) ClearUpdatedAt() *EmailChangeUpsertOne {
	return u.Update(func(s *EmailChangeUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *EmailChangeUpsertOne) SetUserID(v uuid.UUID) *EmailChangeUpsertOne {
	return u.Update(func(s *EmailChangeUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *EmailChangeUpsertOne) UpdateUserID() *EmailChangeUpsertOne {
	return u.Update(func(s *EmailChangeUpsert) {
		s.UpdateUserID()
	})
}

// SetNewEmail sets the "new_email" field.
func (u *EmailChangeUpsertOne) SetNewEmail(v string) *EmailChangeUpsertOne {
	return u.Update(func(s *EmailChangeUpsert) {
		s.SetNewEmail(v)
	})
}

// UpdateNewEmail sets the "new_email" field to the value that was provided on create.
func (u *EmailChangeUpsertOne) UpdateNewEmail() *EmailChangeUpsertOne {
	return u.Update(func(s *EmailChangeUpsert) {
		s.UpdateNewEmail()
	})
}

// SetCodeHash sets the "code_hash" field.
func (u *EmailChangeUpsertOne) SetCodeHash(v string) *EmailChangeUpsertOne {
	return u.Update(func(s *EmailChangeUpsert) {
		s.SetCodeHash(v)
	})
}

// UpdateCodeHash sets the "code_hash" field to the value that was provided on create.
func (u *EmailChangeUpsertOne) UpdateCodeHash() *EmailChangeUpsertOne {
	return u.Update(func(s *EmailChangeUpsert) {
		s.UpdateCodeHash()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *EmailChangeUpsertOne) SetExpiresAt(v time.Time) *EmailChangeUpsertOne {
	return u.Update(func(s *EmailChangeUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *EmailChangeUpsertOne) UpdateExpiresAt() *EmailChangeUpsertOne {
	return u.Update(func(s *EmailChangeUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetAttempts sets the "attempts" field.
func (u *EmailChangeUpsertOne) SetAttempts(v int) *EmailChangeUpsertOne {
	return u.Update(func(s *EmailChangeUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *EmailChangeUpsertOne) AddAttempts(v int) *EmailChangeUpsertOne {
	return u.Update(func(s *EmailChangeUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *EmailChangeUpsertOne) UpdateAttempts() *EmailChangeUpsertOne {
	return u.Update(func(s *EmailChangeUpsert) {
		s.UpdateAttempts()
	})
}

// SetConsumedAt sets the "consumed_at" field.
func (u *EmailChangeUpsertOne) SetConsumedAt(v time.Time) *EmailChangeUpsertOne {
	return u.Update(func(s *EmailChangeUpsert) {
		s.SetConsumedAt(v)
	})
}

// UpdateConsumedAt sets the "consumed_at" field to the value that was provided on create.
func (u *EmailChangeUpsertOne) UpdateConsumedAt() *EmailChangeUpsertOne {
	return u.Update(func(s *EmailChangeUpsert) {
		s.UpdateConsumedAt()
	})
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (u *EmailChangeUpsertOne) ClearConsumedAt() *EmailChangeUpsertOne {
	return u.Update(func(s *EmailChangeUpsert) {
		s.ClearConsumedAt()
	})
}

// Exec executes the query.
func (u *EmailChangeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EmailChangeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EmailChangeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EmailChangeUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: EmailChangeUpsertOne.ID is not supported by MySQL driver. Use EmailChangeUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EmailChangeUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// EmailChangeCreateBulk is the builder for creating many EmailChange entities in bulk.
type EmailChangeCreateBulk struct {
	config
	err      error
	builders []*EmailChangeCreate
	conflict []sql.ConflictOption
}

// Save creates the EmailChange entities in the database.
func (_c *EmailChangeCreateBulk) Save(ctx context.Context) ([]*EmailChange, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EmailChange, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EmailChangeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EmailChangeCreateBulk) SaveX(ctx context.Context) []*EmailChange {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EmailChangeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EmailChangeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EmailChange.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EmailChangeUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *EmailChangeCreateBulk) OnConflict(opts ...sql.ConflictOption) *EmailChangeUpsertBulk {
	_c.conflict = opts
	return &EmailChangeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EmailChange.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EmailChangeCreateBulk) OnConflictColumns(columns ...string) *EmailChangeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EmailChangeUpsertBulk{
		create: _c,
	}
}

// EmailChangeUpsertBulk is the builder for "upsert"-ing
// a bulk of EmailChange nodes.
type EmailChangeUpsertBulk struct {
	create *EmailChangeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.EmailChange.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(emailchange.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *EmailChangeUpsertBulk) UpdateNewValues() *EmailChangeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(emailchange.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(emailchange.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EmailChange.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EmailChangeUpsertBulk) Ignore() *EmailChangeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EmailChangeUpsertBulk) DoNothing() *EmailChangeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EmailChangeCreateBulk.OnConflict
// documentation for more info.
func (u *EmailChangeUpsertBulk) Update(set func(*EmailChangeUpsert)) *EmailChangeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EmailChangeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EmailChangeUpsertBulk) SetUpdatedAt(v time.Time) *EmailChangeUpsertBulk {
	return u.Update(func(s *EmailChangeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EmailChangeUpsertBulk) UpdateUpdatedAt() *EmailChangeUpsertBulk {
	return u.Update(func(s *EmailChangeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *EmailChangeUpsertBulk) ClearUpdatedAt() *EmailChangeUpsertBulk {
	return u.Update(func(s *EmailChangeUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *EmailChangeUpsertBulk) SetUserID(v uuid.UUID) *EmailChangeUpsertBulk {
	return u.Update(func(s *EmailChangeUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *EmailChangeUpsertBulk) UpdateUserID() *EmailChangeUpsertBulk {
	return u.Update(func(s *EmailChangeUpsert) {
		s.UpdateUserID()
	})
}

// SetNewEmail sets the "new_email" field.
func (u *EmailChangeUpsertBulk) SetNewEmail(v string) *EmailChangeUpsertBulk {
	return u.Update(func(s *EmailChangeUpsert) {
		s.SetNewEmail(v)
	})
}

// UpdateNewEmail sets the "new_email" field to the value that was provided on create.
func (u *EmailChangeUpsertBulk) UpdateNewEmail() *EmailChangeUpsertBulk {
	return u.Update(func(s *EmailChangeUpsert) {
		s.UpdateNewEmail()
	})
}

// SetCodeHash sets the "code_hash" field.
func (u *EmailChangeUpsertBulk) SetCodeHash(v string) *EmailChangeUpsertBulk {
	return u.Update(func(s *EmailChangeUpsert) {
		s.SetCodeHash(v)
	})
}

// UpdateCodeHash sets the "code_hash" field to the value that was provided on create.
func (u *EmailChangeUpsertBulk) UpdateCodeHash() *EmailChangeUpsertBulk {
	return u.Update(func(s *EmailChangeUpsert) {
		s.UpdateCodeHash()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *EmailChangeUpsertBulk) SetExpiresAt(v time.Time) *EmailChangeUpsertBulk {
	return u.Update(func(s *EmailChangeUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *EmailChangeUpsertBulk) UpdateExpiresAt() *EmailChangeUpsertBulk {
	return u.Update(func(s *EmailChangeUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetAttempts sets the "attempts" field.
func (u *EmailChangeUpsertBulk) SetAttempts(v int) *EmailChangeUpsertBulk {
	return u.Update(func(s *EmailChangeUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *EmailChangeUpsertBulk) AddAttempts(v int) *EmailChangeUpsertBulk {
	return u.Update(func(s *EmailChangeUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *EmailChangeUpsertBulk) UpdateAttempts() *EmailChangeUpsertBulk {
	return u.Update(func(s *EmailChangeUpsert) {
		s.UpdateAttempts()
	})
}

// SetConsumedAt sets the "consumed_at" field.
func (u *EmailChangeUpsertBulk) SetConsumedAt(v time.Time) *EmailChangeUpsertBulk {
	return u.Update(func(s *EmailChangeUpsert) {
		s.SetConsumedAt(v)
	})
}

// UpdateConsumedAt sets the "consumed_at" field to the value that was provided on create.
func (u *EmailChangeUpsertBulk) UpdateConsumedAt() *EmailChangeUpsertBulk {
	return u.Update(func(s *EmailChangeUpsert) {
		s.UpdateConsumedAt()
	})
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (u *EmailChangeUpsertBulk) ClearConsumedAt() *EmailChangeUpsertBulk {
	return u.Update(func(s *EmailChangeUpsert) {
		s.ClearConsumedAt()
	})
}

// Exec executes the query.
func (u *EmailChangeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EmailChangeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EmailChangeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EmailChangeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
