// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/emailchange"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/predicate"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/user"
)

// EmailChangeUpdate is the builder for updating EmailChange entities.
type EmailChangeUpdate struct {
	config
	hooks     []Hook
	mutation  *EmailChangeMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the EmailChangeUpdate builder.
func (_u *EmailChangeUpdate) Where(ps ...predicate.EmailChange) *EmailChangeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EmailChangeUpdate) SetUpdatedAt(v time.Time) *EmailChangeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *EmailChangeUpdate) SetUserID(v uuid.UUID) *EmailChangeUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *EmailChangeUpdate) SetNillableUserID(v *uuid.UUID) *EmailChangeUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetNewEmail sets the "new_email" field.
func (_u *EmailChangeUpdate) SetNewEmail(v string) *EmailChangeUpdate {
	_u.mutation.SetNewEmail(v)
	return _u
}

// SetNillableNewEmail sets the "new_email" field if the given value is not nil.
func (_u *EmailChangeUpdate) SetNillableNewEmail(v *string) *EmailChangeUpdate {
	if v != nil {
		_u.SetNewEmail(*v)
	}
	return _u
}

// SetCodeHash sets the "code_hash" field.
func (_u *EmailChangeUpdate) SetCodeHash(v string) *EmailChangeUpdate {
	_u.mutation.SetCodeHash(v)
	return _u
}

// SetNillableCodeHash sets the "code_hash" field if the given value is not nil.
func (_u *EmailChangeUpdate) SetNillableCodeHash(v *string) *EmailChangeUpdate {
	if v != nil {
		_u.SetCodeHash(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *EmailChangeUpdate) SetExpiresAt(v time.Time) *EmailChangeUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *EmailChangeUpdate) SetNillableExpiresAt(v *time.Time) *EmailChangeUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *EmailChangeUpdate) SetAttempts(v int) *EmailChangeUpdate {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *EmailChangeUpdate) SetNillableAttempts(v *int) *EmailChangeUpdate {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *EmailChangeUpdate) AddAttempts(v int) *EmailChangeUpdate {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *EmailChangeUpdate) SetConsumedAt(v time.Time) *EmailChangeUpdate {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *EmailChangeUpdate) SetNillableConsumedAt(v *time.Time) *EmailChangeUpdate {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *EmailChangeUpdate) ClearConsumedAt() *EmailChangeUpdate {
	_u.mutation.ClearConsumedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *EmailChangeUpdate) SetUser(v *User) *EmailChangeUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the EmailChangeMutation object of the builder.
func (_u *EmailChangeUpdate) Mutation() *EmailChangeMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *EmailChangeUpdate) ClearUser() *EmailChangeUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EmailChangeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmailChangeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EmailChangeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmailChangeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EmailChangeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := emailchange.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EmailChangeUpdate) check() error {
	if v, ok := _u.mutation.NewEmail(); ok {
		if err := emailchange.NewEmailValidator(v); err != nil {
			return &ValidationError{Name: "new_email", err: fmt.Errorf(`ent: validator failed for field "EmailChange.new_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CodeHash(); ok {
		if err := emailchange.CodeHashValidator(v); err != nil {
			return &ValidationError{Name: "code_hash", err: fmt.Errorf(`ent: validator failed for field "EmailChange.code_hash": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EmailChange.user"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *EmailChangeUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *EmailChangeUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *EmailChangeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(emailchange.Table, emailchange.Columns, sqlgraph.NewFieldSpec(emailchange.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(emailchange.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.NewEmail(); ok {
		_spec.SetField(emailchange.FieldNewEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodeHash(); ok {
		_spec.SetField(emailchange.FieldCodeHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(emailchange.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(emailchange.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(emailchange.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(emailchange.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(emailchange.FieldConsumedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   emailchange.UserTable,
			Columns: []string{emailchange.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   emailchange.UserTable,
			Columns: []string{emailchange.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{emailchange.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EmailChangeUpdateOne is the builder for updating a single EmailChange entity.
type EmailChangeUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *EmailChangeMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EmailChangeUpdateOne) SetUpdatedAt(v time.Time) *EmailChangeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *EmailChangeUpdateOne) SetUserID(v uuid.UUID) *EmailChangeUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *EmailChangeUpdateOne) SetNillableUserID(v *uuid.UUID) *EmailChangeUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetNewEmail sets the "new_email" field.
func (_u *EmailChangeUpdateOne) SetNewEmail(v string) *EmailChangeUpdateOne {
	_u.mutation.SetNewEmail(v)
	return _u
}

// SetNillableNewEmail sets the "new_email" field if the given value is not nil.
func (_u *EmailChangeUpdateOne) SetNillableNewEmail(v *string) *EmailChangeUpdateOne {
	if v != nil {
		_u.SetNewEmail(*v)
	}
	return _u
}

// SetCodeHash sets the "code_hash" field.
func (_u *EmailChangeUpdateOne) SetCodeHash(v string) *EmailChangeUpdateOne {
	_u.mutation.SetCodeHash(v)
	return _u
}

// SetNillableCodeHash sets the "code_hash" field if the given value is not nil.
func (_u *EmailChangeUpdateOne) SetNillableCodeHash(v *string) *EmailChangeUpdateOne {
	if v != nil {
		_u.SetCodeHash(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *EmailChangeUpdateOne) SetExpiresAt(v time.Time) *EmailChangeUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *EmailChangeUpdateOne) SetNillableExpiresAt(v *time.Time) *EmailChangeUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *EmailChangeUpdateOne) SetAttempts(v int) *EmailChangeUpdateOne {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *EmailChangeUpdateOne) SetNillableAttempts(v *int) *EmailChangeUpdateOne {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *EmailChangeUpdateOne) AddAttempts(v int) *EmailChangeUpdateOne {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *EmailChangeUpdateOne) SetConsumedAt(v time.Time) *EmailChangeUpdateOne {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *EmailChangeUpdateOne) SetNillableConsumedAt(v *time.Time) *EmailChangeUpdateOne {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *EmailChangeUpdateOne) ClearConsumedAt() *EmailChangeUpdateOne {
	_u.mutation.ClearConsumedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *EmailChangeUpdateOne) SetUser(v *User) *EmailChangeUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the EmailChangeMutation object of the builder.
func (_u *EmailChangeUpdateOne) Mutation() *EmailChangeMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *EmailChangeUpdateOne) ClearUser() *EmailChangeUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the EmailChangeUpdate builder.
func (_u *EmailChangeUpdateOne) Where(ps ...predicate.EmailChange) *EmailChangeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EmailChangeUpdateOne) Select(field string, fields ...string) *EmailChangeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EmailChange entity.
func (_u *EmailChangeUpdateOne) Save(ctx context.Context) (*EmailChange, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmailChangeUpdateOne) SaveX(ctx context.Context) *EmailChange {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EmailChangeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmailChangeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EmailChangeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := emailchange.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EmailChangeUpdateOne) check() error {
	if v, ok := _u.mutation.NewEmail(); ok {
		if err := emailchange.NewEmailValidator(v); err != nil {
			return &ValidationError{Name: "new_email", err: fmt.Errorf(`ent: validator failed for field "EmailChange.new_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CodeHash(); ok {
		if err := emailchange.CodeHashValidator(v); err != nil {
			return &ValidationError{Name: "code_hash", err: fmt.Errorf(`ent: validator failed for field "EmailChange.code_hash": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EmailChange.user"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *EmailChangeUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *EmailChangeUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *EmailChangeUpdateOne) sqlSave(ctx context.Context) (_node *EmailChange, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(emailchange.Table, emailchange.Columns, sqlgraph.NewFieldSpec(emailchange.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EmailChange.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, emailchange.FieldID)
		for _, f := range fields {
			if !emailchange.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != emailchange.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(emailchange.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.NewEmail(); ok {
		_spec.SetField(emailchange.FieldNewEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodeHash(); ok {
		_spec.SetField(emailchange.FieldCodeHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(emailchange.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(emailchange.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(emailchange.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(emailchange.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(emailchange.FieldConsumedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   emailchange.UserTable,
			Columns: []string{emailchange.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   emailchange.UserTable,
			Columns: []string{emailchange.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &EmailChange{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{emailchange.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
