// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/invitation"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/invitationrole"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/role"
)

// InvitationRole is the model entity for the InvitationRole schema.
type InvitationRole struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// InvitationID holds the value of the "invitation_id" field.
	InvitationID uuid.UUID `json:"invitation_id,omitempty"`
	// RoleID holds the value of the "role_id" field.
	RoleID uuid.UUID `json:"role_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the InvitationRoleQuery when eager-loading is set.
	Edges        InvitationRoleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// InvitationRoleEdges holds the relations/edges for other nodes in the graph.
type InvitationRoleEdges struct {
	// Invitation holds the value of the invitation edge.
	Invitation *Invitation `json:"invitation,omitempty"`
	// Role holds the value of the role edge.
	Role *Role `json:"role,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// InvitationOrErr returns the Invitation value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InvitationRoleEdges) InvitationOrErr() (*Invitation, error) {
	if e.Invitation != nil {
		return e.Invitation, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: invitation.Label}
	}
	return nil, &NotLoadedError{edge: "invitation"}
}

// RoleOrErr returns the Role value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InvitationRoleEdges) RoleOrErr() (*Role, error) {
	if e.Role != nil {
		return e.Role, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: role.Label}
	}
	return nil, &NotLoadedError{edge: "role"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InvitationRole) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case invitationrole.FieldCreatedAt, invitationrole.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case invitationrole.FieldID, invitationrole.FieldInvitationID, invitationrole.FieldRoleID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InvitationRole fields.
func (_m *InvitationRole) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case invitationrole.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case invitationrole.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case invitationrole.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case invitationrole.FieldInvitationID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field invitation_id", values[i])
			} else if value != nil {
				_m.InvitationID = *value
			}
		case invitationrole.FieldRoleID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field role_id", values[i])
			} else if value != nil {
				_m.RoleID = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InvitationRole.
// This includes values selected through modifiers, order, etc.
func (_m *InvitationRole) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryInvitation queries the "invitation" edge of the InvitationRole entity.
func (_m *InvitationRole) QueryInvitation() *InvitationQuery {
	return NewInvitationRoleClient(_m.config).QueryInvitation(_m)
}

// QueryRole queries the "role" edge of the InvitationRole entity.
func (_m *InvitationRole) QueryRole() *RoleQuery {
	return NewInvitationRoleClient(_m.config).QueryRole(_m)
}

// Update returns a builder for updating this InvitationRole.
// Note that you need to call InvitationRole.Unwrap() before calling this method if this InvitationRole
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *InvitationRole) Update() *InvitationRoleUpdateOne {
	return NewInvitationRoleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the InvitationRole entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *InvitationRole) Unwrap() *InvitationRole {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: InvitationRole is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *InvitationRole) String() string {
	var builder strings.Builder
	builder.WriteString("InvitationRole(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("invitation_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InvitationID))
	builder.WriteString(", ")
	builder.WriteString("role_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RoleID))
	builder.WriteByte(')')
	return builder.String()
}

// InvitationRoles is a parsable slice of InvitationRole.
type InvitationRoles []*InvitationRole
