// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/membership"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/membershiprole"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/predicate"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/role"
)

// MembershipRoleUpdate is the builder for updating MembershipRole entities.
type MembershipRoleUpdate struct {
	config
	hooks     []Hook
	mutation  *MembershipRoleMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the MembershipRoleUpdate builder.
func (_u *MembershipRoleUpdate) Where(ps ...predicate.MembershipRole) *MembershipRoleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MembershipRoleUpdate) SetUpdatedAt(v time.Time) *MembershipRoleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *MembershipRoleUpdate) ClearUpdatedAt() *MembershipRoleUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetMembershipID sets the "membership_id" field.
func (_u *MembershipRoleUpdate) SetMembershipID(v uuid.UUID) *MembershipRoleUpdate {
	_u.mutation.SetMembershipID(v)
	return _u
}

// SetNillableMembershipID sets the "membership_id" field if the given value is not nil.
func (_u *MembershipRoleUpdate) SetNillableMembershipID(v *uuid.UUID) *MembershipRoleUpdate {
	if v != nil {
		_u.SetMembershipID(*v)
	}
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *MembershipRoleUpdate) SetRoleID(v uuid.UUID) *MembershipRoleUpdate {
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *MembershipRoleUpdate) SetNillableRoleID(v *uuid.UUID) *MembershipRoleUpdate {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// SetGrantedBy sets the "granted_by" field.
func (_u *MembershipRoleUpdate) SetGrantedBy(v uuid.UUID) *MembershipRoleUpdate {
	_u.mutation.SetGrantedBy(v)
	return _u
}

// SetNillableGrantedBy sets the "granted_by" field if the given value is not nil.
func (_u *MembershipRoleUpdate) SetNillableGrantedBy(v *uuid.UUID) *MembershipRoleUpdate {
	if v != nil {
		_u.SetGrantedBy(*v)
	}
	return _u
}

// ClearGrantedBy clears the value of the "granted_by" field.
func (_u *MembershipRoleUpdate) ClearGrantedBy() *MembershipRoleUpdate {
	_u.mutation.ClearGrantedBy()
	return _u
}

// SetMembership sets the "membership" edge to the Membership entity.
func (_u *MembershipRoleUpdate) SetMembership(v *Membership) *MembershipRoleUpdate {
	return _u.SetMembershipID(v.ID)
}

// SetRole sets the "role" edge to the Role entity.
func (_u *MembershipRoleUpdate) SetRole(v *Role) *MembershipRoleUpdate {
	return _u.SetRoleID(v.ID)
}

// Mutation returns the MembershipRoleMutation object of the builder.
func (_u *MembershipRoleUpdate) Mutation() *MembershipRoleMutation {
	return _u.mutation
}

// ClearMembership clears the "membership" edge to the Membership entity.
func (_u *MembershipRoleUpdate) ClearMembership() *MembershipRoleUpdate {
	_u.mutation.ClearMembership()
	return _u
}

// ClearRole clears the "role" edge to the Role entity.
func (_u *MembershipRoleUpdate) ClearRole() *MembershipRoleUpdate {
	_u.mutation.ClearRole()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MembershipRoleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MembershipRoleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MembershipRoleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MembershipRoleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MembershipRoleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := membershiprole.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MembershipRoleUpdate) check() error {
	if _u.mutation.MembershipCleared() && len(_u.mutation.MembershipIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MembershipRole.membership"`)
	}
	if _u.mutation.RoleCleared() && len(_u.mutation.RoleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MembershipRole.role"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *MembershipRoleUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *MembershipRoleUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *MembershipRoleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(membershiprole.Table, membershiprole.Columns, sqlgraph.NewFieldSpec(membershiprole.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(membershiprole.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(membershiprole.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(membershiprole.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.GrantedBy(); ok {
		_spec.SetField(membershiprole.FieldGrantedBy, field.TypeUUID, value)
	}
	if _u.mutation.GrantedByCleared() {
		_spec.ClearField(membershiprole.FieldGrantedBy, field.TypeUUID)
	}
	if _u.mutation.MembershipCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   membershiprole.MembershipTable,
			Columns: []string{membershiprole.MembershipColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(membership.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembershipIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   membershiprole.MembershipTable,
			Columns: []string{membershiprole.MembershipColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(membership.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   membershiprole.RoleTable,
			Columns: []string{membershiprole.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   membershiprole.RoleTable,
			Columns: []string{membershiprole.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{membershiprole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MembershipRoleUpdateOne is the builder for updating a single MembershipRole entity.
type MembershipRoleUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *MembershipRoleMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MembershipRoleUpdateOne) SetUpdatedAt(v time.Time) *MembershipRoleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *MembershipRoleUpdateOne) ClearUpdatedAt() *MembershipRoleUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetMembershipID sets the "membership_id" field.
func (_u *MembershipRoleUpdateOne) SetMembershipID(v uuid.UUID) *MembershipRoleUpdateOne {
	_u.mutation.SetMembershipID(v)
	return _u
}

// SetNillableMembershipID sets the "membership_id" field if the given value is not nil.
func (_u *MembershipRoleUpdateOne) SetNillableMembershipID(v *uuid.UUID) *MembershipRoleUpdateOne {
	if v != nil {
		_u.SetMembershipID(*v)
	}
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *MembershipRoleUpdateOne) SetRoleID(v uuid.UUID) *MembershipRoleUpdateOne {
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *MembershipRoleUpdateOne) SetNillableRoleID(v *uuid.UUID) *MembershipRoleUpdateOne {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// SetGrantedBy sets the "granted_by" field.
func (_u *MembershipRoleUpdateOne) SetGrantedBy(v uuid.UUID) *MembershipRoleUpdateOne {
	_u.mutation.SetGrantedBy(v)
	return _u
}

// SetNillableGrantedBy sets the "granted_by" field if the given value is not nil.
func (_u *MembershipRoleUpdateOne) SetNillableGrantedBy(v *uuid.UUID) *MembershipRoleUpdateOne {
	if v != nil {
		_u.SetGrantedBy(*v)
	}
	return _u
}

// ClearGrantedBy clears the value of the "granted_by" field.
func (_u *MembershipRoleUpdateOne) ClearGrantedBy() *MembershipRoleUpdateOne {
	_u.mutation.ClearGrantedBy()
	return _u
}

// SetMembership sets the "membership" edge to the Membership entity.
func (_u *MembershipRoleUpdateOne) SetMembership(v *Membership) *MembershipRoleUpdateOne {
	return _u.SetMembershipID(v.ID)
}

// SetRole sets the "role" edge to the Role entity.
func (_u *MembershipRoleUpdateOne) SetRole(v *Role) *MembershipRoleUpdateOne {
	return _u.SetRoleID(v.ID)
}

// Mutation returns the MembershipRoleMutation object of the builder.
func (_u *MembershipRoleUpdateOne) Mutation() *MembershipRoleMutation {
	return _u.mutation
}

// ClearMembership clears the "membership" edge to the Membership entity.
func (_u *MembershipRoleUpdateOne) ClearMembership() *MembershipRoleUpdateOne {
	_u.mutation.ClearMembership()
	return _u
}

// ClearRole clears the "role" edge to the Role entity.
func (_u *MembershipRoleUpdateOne) ClearRole() *MembershipRoleUpdateOne {
	_u.mutation.ClearRole()
	return _u
}

// Where appends a list predicates to the MembershipRoleUpdate builder.
func (_u *MembershipRoleUpdateOne) Where(ps ...predicate.MembershipRole) *MembershipRoleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MembershipRoleUpdateOne) Select(field string, fields ...string) *MembershipRoleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MembershipRole entity.
func (_u *MembershipRoleUpdateOne) Save(ctx context.Context) (*MembershipRole, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MembershipRoleUpdateOne) SaveX(ctx context.Context) *MembershipRole {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MembershipRoleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MembershipRoleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MembershipRoleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := membershiprole.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MembershipRoleUpdateOne) check() error {
	if _u.mutation.MembershipCleared() && len(_u.mutation.MembershipIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MembershipRole.membership"`)
	}
	if _u.mutation.RoleCleared() && len(_u.mutation.RoleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MembershipRole.role"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *MembershipRoleUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *MembershipRoleUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *MembershipRoleUpdateOne) sqlSave(ctx context.Context) (_node *MembershipRole, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(membershiprole.Table, membershiprole.Columns, sqlgraph.NewFieldSpec(membershiprole.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MembershipRole.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, membershiprole.FieldID)
		for _, f := range fields {
			if !membershiprole.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != membershiprole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(membershiprole.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(membershiprole.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(membershiprole.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.GrantedBy(); ok {
		_spec.SetField(membershiprole.FieldGrantedBy, field.TypeUUID, value)
	}
	if _u.mutation.GrantedByCleared() {
		_spec.ClearField(membershiprole.FieldGrantedBy, field.TypeUUID)
	}
	if _u.mutation.MembershipCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   membershiprole.MembershipTable,
			Columns: []string{membershiprole.MembershipColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(membership.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembershipIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   membershiprole.MembershipTable,
			Columns: []string{membershiprole.MembershipColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(membership.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   membershiprole.RoleTable,
			Columns: []string{membershiprole.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   membershiprole.RoleTable,
			Columns: []string{membershiprole.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &MembershipRole{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{membershiprole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
