// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/predicate"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/role"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/rolepermission"
)

// RolePermissionUpdate is the builder for updating RolePermission entities.
type RolePermissionUpdate struct {
	config
	hooks     []Hook
	mutation  *RolePermissionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the RolePermissionUpdate builder.
func (_u *RolePermissionUpdate) Where(ps ...predicate.RolePermission) *RolePermissionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RolePermissionUpdate) SetUpdatedAt(v time.Time) *RolePermissionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *RolePermissionUpdate) ClearUpdatedAt() *RolePermissionUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *RolePermissionUpdate) SetRoleID(v uuid.UUID) *RolePermissionUpdate {
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *RolePermissionUpdate) SetNillableRoleID(v *uuid.UUID) *RolePermissionUpdate {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// SetPermissionKey sets the "permission_key" field.
func (_u *RolePermissionUpdate) SetPermissionKey(v string) *RolePermissionUpdate {
	_u.mutation.SetPermissionKey(v)
	return _u
}

// SetNillablePermissionKey sets the "permission_key" field if the given value is not nil.
func (_u *RolePermissionUpdate) SetNillablePermissionKey(v *string) *RolePermissionUpdate {
	if v != nil {
		_u.SetPermissionKey(*v)
	}
	return _u
}

// SetRole sets the "role" edge to the Role entity.
func (_u *RolePermissionUpdate) SetRole(v *Role) *RolePermissionUpdate {
	return _u.SetRoleID(v.ID)
}

// Mutation returns the RolePermissionMutation object of the builder.
func (_u *RolePermissionUpdate) Mutation() *RolePermissionMutation {
	return _u.mutation
}

// ClearRole clears the "role" edge to the Role entity.
func (_u *RolePermissionUpdate) ClearRole() *RolePermissionUpdate {
	_u.mutation.ClearRole()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RolePermissionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RolePermissionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RolePermissionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RolePermissionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RolePermissionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := rolepermission.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RolePermissionUpdate) check() error {
	if v, ok := _u.mutation.PermissionKey(); ok {
		if err := rolepermission.PermissionKeyValidator(v); err != nil {
			return &ValidationError{Name: "permission_key", err: fmt.Errorf(`ent: validator failed for field "RolePermission.permission_key": %w`, err)}
		}
	}
	if _u.mutation.RoleCleared() && len(_u.mutation.RoleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RolePermission.role"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *RolePermissionUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RolePermissionUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *RolePermissionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rolepermission.Table, rolepermission.Columns, sqlgraph.NewFieldSpec(rolepermission.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(rolepermission.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rolepermission.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(rolepermission.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PermissionKey(); ok {
		_spec.SetField(rolepermission.FieldPermissionKey, field.TypeString, value)
	}
	if _u.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rolepermission.RoleTable,
			Columns: []string{rolepermission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rolepermission.RoleTable,
			Columns: []string{rolepermission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rolepermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RolePermissionUpdateOne is the builder for updating a single RolePermission entity.
type RolePermissionUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *RolePermissionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RolePermissionUpdateOne) SetUpdatedAt(v time.Time) *RolePermissionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *RolePermissionUpdateOne) ClearUpdatedAt() *RolePermissionUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *RolePermissionUpdateOne) SetRoleID(v uuid.UUID) *RolePermissionUpdateOne {
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *RolePermissionUpdateOne) SetNillableRoleID(v *uuid.UUID) *RolePermissionUpdateOne {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// SetPermissionKey sets the "permission_key" field.
func (_u *RolePermissionUpdateOne) SetPermissionKey(v string) *RolePermissionUpdateOne {
	_u.mutation.SetPermissionKey(v)
	return _u
}

// SetNillablePermissionKey sets the "permission_key" field if the given value is not nil.
func (_u *RolePermissionUpdateOne) SetNillablePermissionKey(v *string) *RolePermissionUpdateOne {
	if v != nil {
		_u.SetPermissionKey(*v)
	}
	return _u
}

// SetRole sets the "role" edge to the Role entity.
func (_u *RolePermissionUpdateOne) SetRole(v *Role) *RolePermissionUpdateOne {
	return _u.SetRoleID(v.ID)
}

// Mutation returns the RolePermissionMutation object of the builder.
func (_u *RolePermissionUpdateOne) Mutation() *RolePermissionMutation {
	return _u.mutation
}

// ClearRole clears the "role" edge to the Role entity.
func (_u *RolePermissionUpdateOne) ClearRole() *RolePermissionUpdateOne {
	_u.mutation.ClearRole()
	return _u
}

// Where appends a list predicates to the RolePermissionUpdate builder.
func (_u *RolePermissionUpdateOne) Where(ps ...predicate.RolePermission) *RolePermissionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RolePermissionUpdateOne) Select(field string, fields ...string) *RolePermissionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RolePermission entity.
func (_u *RolePermissionUpdateOne) Save(ctx context.Context) (*RolePermission, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RolePermissionUpdateOne) SaveX(ctx context.Context) *RolePermission {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RolePermissionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RolePermissionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RolePermissionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := rolepermission.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RolePermissionUpdateOne) check() error {
	if v, ok := _u.mutation.PermissionKey(); ok {
		if err := rolepermission.PermissionKeyValidator(v); err != nil {
			return &ValidationError{Name: "permission_key", err: fmt.Errorf(`ent: validator failed for field "RolePermission.permission_key": %w`, err)}
		}
	}
	if _u.mutation.RoleCleared() && len(_u.mutation.RoleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RolePermission.role"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *RolePermissionUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RolePermissionUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *RolePermissionUpdateOne) sqlSave(ctx context.Context) (_node *RolePermission, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rolepermission.Table, rolepermission.Columns, sqlgraph.NewFieldSpec(rolepermission.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RolePermission.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rolepermission.FieldID)
		for _, f := range fields {
			if !rolepermission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rolepermission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(rolepermission.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rolepermission.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(rolepermission.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PermissionKey(); ok {
		_spec.SetField(rolepermission.FieldPermissionKey, field.TypeString, value)
	}
	if _u.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rolepermission.RoleTable,
			Columns: []string{rolepermission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rolepermission.RoleTable,
			Columns: []string{rolepermission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &RolePermission{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rolepermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
