// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/device"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/twofactorchallenge"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/user"
)

// TwoFactorChallenge is the model entity for the TwoFactorChallenge schema.
type TwoFactorChallenge struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// DeviceID holds the value of the "device_id" field.
	DeviceID uuid.UUID `json:"device_id,omitempty"`
	// CodeHash holds the value of the "code_hash" field.
	CodeHash string `json:"-"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// Attempts holds the value of the "attempts" field.
	Attempts int `json:"attempts,omitempty"`
	// ConsumedAt holds the value of the "consumed_at" field.
	ConsumedAt *time.Time `json:"consumed_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TwoFactorChallengeQuery when eager-loading is set.
	Edges        TwoFactorChallengeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TwoFactorChallengeEdges holds the relations/edges for other nodes in the graph.
type TwoFactorChallengeEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Device holds the value of the device edge.
	Device *Device `json:"device,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TwoFactorChallengeEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// DeviceOrErr returns the Device value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TwoFactorChallengeEdges) DeviceOrErr() (*Device, error) {
	if e.Device != nil {
		return e.Device, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: device.Label}
	}
	return nil, &NotLoadedError{edge: "device"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TwoFactorChallenge) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case twofactorchallenge.FieldAttempts:
			values[i] = new(sql.NullInt64)
		case twofactorchallenge.FieldCodeHash:
			values[i] = new(sql.NullString)
		case twofactorchallenge.FieldCreatedAt, twofactorchallenge.FieldUpdatedAt, twofactorchallenge.FieldExpiresAt, twofactorchallenge.FieldConsumedAt:
			values[i] = new(sql.NullTime)
		case twofactorchallenge.FieldID, twofactorchallenge.FieldUserID, twofactorchallenge.FieldDeviceID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TwoFactorChallenge fields.
func (_m *TwoFactorChallenge) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case twofactorchallenge.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case twofactorchallenge.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case twofactorchallenge.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case twofactorchallenge.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case twofactorchallenge.FieldDeviceID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field device_id", values[i])
			} else if value != nil {
				_m.DeviceID = *value
			}
		case twofactorchallenge.FieldCodeHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code_hash", values[i])
			} else if value.Valid {
				_m.CodeHash = value.String
			}
		case twofactorchallenge.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case twofactorchallenge.FieldAttempts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempts", values[i])
			} else if value.Valid {
				_m.Attempts = int(value.Int64)
			}
		case twofactorchallenge.FieldConsumedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field consumed_at", values[i])
			} else if value.Valid {
				_m.ConsumedAt = new(time.Time)
				*_m.ConsumedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TwoFactorChallenge.
// This includes values selected through modifiers, order, etc.
func (_m *TwoFactorChallenge) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the TwoFactorChallenge entity.
func (_m *TwoFactorChallenge) QueryUser() *UserQuery {
	return NewTwoFactorChallengeClient(_m.config).QueryUser(_m)
}

// QueryDevice queries the "device" edge of the TwoFactorChallenge entity.
func (_m *TwoFactorChallenge) QueryDevice() *DeviceQuery {
	return NewTwoFactorChallengeClient(_m.config).QueryDevice(_m)
}

// Update returns a builder for updating this TwoFactorChallenge.
// Note that you need to call TwoFactorChallenge.Unwrap() before calling this method if this TwoFactorChallenge
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TwoFactorChallenge) Update() *TwoFactorChallengeUpdateOne {
	return NewTwoFactorChallengeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TwoFactorChallenge entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TwoFactorChallenge) Unwrap() *TwoFactorChallenge {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TwoFactorChallenge is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TwoFactorChallenge) String() string {
	var builder strings.Builder
	builder.WriteString("TwoFactorChallenge(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("device_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeviceID))
	builder.WriteString(", ")
	builder.WriteString("code_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("attempts=")
	builder.WriteString(fmt.Sprintf("%v", _m.Attempts))
	builder.WriteString(", ")
	if v := _m.ConsumedAt; v != nil {
		builder.WriteString("consumed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// TwoFactorChallenges is a parsable slice of TwoFactorChallenge.
type TwoFactorChallenges []*TwoFactorChallenge
