// Code generated by ent, DO NOT EDIT.

package passwordreset

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldEQ(FieldUserID, v))
}

// CodeHash applies equality check predicate on the "code_hash" field. It's identical to CodeHashEQ.
func CodeHash(v string) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldEQ(FieldCodeHash, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldEQ(FieldExpiresAt, v))
}

// Attempts applies equality check predicate on the "attempts" field. It's identical to AttemptsEQ.
func Attempts(v int) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldEQ(FieldAttempts, v))
}

// ConsumedAt applies equality check predicate on the "consumed_at" field. It's identical to ConsumedAtEQ.
func ConsumedAt(v time.Time) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldEQ(FieldConsumedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldNotNull(FieldUpdatedAt))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldNotIn(FieldUserID, vs...))
}

// CodeHashEQ applies the EQ predicate on the "code_hash" field.
func CodeHashEQ(v string) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldEQ(FieldCodeHash, v))
}

// CodeHashNEQ applies the NEQ predicate on the "code_hash" field.
func CodeHashNEQ(v string) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldNEQ(FieldCodeHash, v))
}

// CodeHashIn applies the In predicate on the "code_hash" field.
func CodeHashIn(vs ...string) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldIn(FieldCodeHash, vs...))
}

// CodeHashNotIn applies the NotIn predicate on the "code_hash" field.
func CodeHashNotIn(vs ...string) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldNotIn(FieldCodeHash, vs...))
}

// CodeHashGT applies the GT predicate on the "code_hash" field.
func CodeHashGT(v string) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldGT(FieldCodeHash, v))
}

// CodeHashGTE applies the GTE predicate on the "code_hash" field.
func CodeHashGTE(v string) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldGTE(FieldCodeHash, v))
}

// CodeHashLT applies the LT predicate on the "code_hash" field.
func CodeHashLT(v string) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldLT(FieldCodeHash, v))
}

// CodeHashLTE applies the LTE predicate on the "code_hash" field.
func CodeHashLTE(v string) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldLTE(FieldCodeHash, v))
}

// CodeHashContains applies the Contains predicate on the "code_hash" field.
func CodeHashContains(v string) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldContains(FieldCodeHash, v))
}

// CodeHashHasPrefix applies the HasPrefix predicate on the "code_hash" field.
func CodeHashHasPrefix(v string) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldHasPrefix(FieldCodeHash, v))
}

// CodeHashHasSuffix applies the HasSuffix predicate on the "code_hash" field.
func CodeHashHasSuffix(v string) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldHasSuffix(FieldCodeHash, v))
}

// CodeHashEqualFold applies the EqualFold predicate on the "code_hash" field.
func CodeHashEqualFold(v string) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldEqualFold(FieldCodeHash, v))
}

// CodeHashContainsFold applies the ContainsFold predicate on the "code_hash" field.
func CodeHashContainsFold(v string) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldContainsFold(FieldCodeHash, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldLTE(FieldExpiresAt, v))
}

// AttemptsEQ applies the EQ predicate on the "attempts" field.
func AttemptsEQ(v int) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldEQ(FieldAttempts, v))
}

// AttemptsNEQ applies the NEQ predicate on the "attempts" field.
func AttemptsNEQ(v int) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldNEQ(FieldAttempts, v))
}

// AttemptsIn applies the In predicate on the "attempts" field.
func AttemptsIn(vs ...int) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldIn(FieldAttempts, vs...))
}

// AttemptsNotIn applies the NotIn predicate on the "attempts" field.
func AttemptsNotIn(vs ...int) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldNotIn(FieldAttempts, vs...))
}

// AttemptsGT applies the GT predicate on the "attempts" field.
func AttemptsGT(v int) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldGT(FieldAttempts, v))
}

// AttemptsGTE applies the GTE predicate on the "attempts" field.
func AttemptsGTE(v int) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldGTE(FieldAttempts, v))
}

// AttemptsLT applies the LT predicate on the "attempts" field.
func AttemptsLT(v int) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldLT(FieldAttempts, v))
}

// AttemptsLTE applies the LTE predicate on the "attempts" field.
func AttemptsLTE(v int) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldLTE(FieldAttempts, v))
}

// ConsumedAtEQ applies the EQ predicate on the "consumed_at" field.
func ConsumedAtEQ(v time.Time) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldEQ(FieldConsumedAt, v))
}

// ConsumedAtNEQ applies the NEQ predicate on the "consumed_at" field.
func ConsumedAtNEQ(v time.Time) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldNEQ(FieldConsumedAt, v))
}

// ConsumedAtIn applies the In predicate on the "consumed_at" field.
func ConsumedAtIn(vs ...time.Time) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldIn(FieldConsumedAt, vs...))
}

// ConsumedAtNotIn applies the NotIn predicate on the "consumed_at" field.
func ConsumedAtNotIn(vs ...time.Time) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldNotIn(FieldConsumedAt, vs...))
}

// ConsumedAtGT applies the GT predicate on the "consumed_at" field.
func ConsumedAtGT(v time.Time) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldGT(FieldConsumedAt, v))
}

// ConsumedAtGTE applies the GTE predicate on the "consumed_at" field.
func ConsumedAtGTE(v time.Time) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldGTE(FieldConsumedAt, v))
}

// ConsumedAtLT applies the LT predicate on the "consumed_at" field.
func ConsumedAtLT(v time.Time) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldLT(FieldConsumedAt, v))
}

// ConsumedAtLTE applies the LTE predicate on the "consumed_at" field.
func ConsumedAtLTE(v time.Time) predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldLTE(FieldConsumedAt, v))
}

// ConsumedAtIsNil applies the IsNil predicate on the "consumed_at" field.
func ConsumedAtIsNil() predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldIsNull(FieldConsumedAt))
}

// ConsumedAtNotNil applies the NotNil predicate on the "consumed_at" field.
func ConsumedAtNotNil() predicate.PasswordReset {
	return predicate.PasswordReset(sql.FieldNotNull(FieldConsumedAt))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.PasswordReset {
	return predicate.PasswordReset(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.PasswordReset {
	return predicate.PasswordReset(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PasswordReset) predicate.PasswordReset {
	return predicate.PasswordReset(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PasswordReset) predicate.PasswordReset {
	return predicate.PasswordReset(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PasswordReset) predicate.PasswordReset {
	return predicate.PasswordReset(sql.NotPredicates(p))
}
