// Code generated by ent, DO NOT EDIT.

package authzevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldEQ(FieldUpdatedAt, v))
}

// OrganizationID applies equality check predicate on the "organization_id" field. It's identical to OrganizationIDEQ.
func OrganizationID(v uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldEQ(FieldOrganizationID, v))
}

// ActorID applies equality check predicate on the "actor_id" field. It's identical to ActorIDEQ.
func ActorID(v uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldEQ(FieldActorID, v))
}

// SubjectID applies equality check predicate on the "subject_id" field. It's identical to SubjectIDEQ.
func SubjectID(v uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldEQ(FieldSubjectID, v))
}

// Action applies equality check predicate on the "action" field. It's identical to ActionEQ.
func Action(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldEQ(FieldAction, v))
}

// RoleID applies equality check predicate on the "role_id" field. It's identical to RoleIDEQ.
func RoleID(v uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldEQ(FieldRoleID, v))
}

// PermissionKey applies equality check predicate on the "permission_key" field. It's identical to PermissionKeyEQ.
func PermissionKey(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldEQ(FieldPermissionKey, v))
}

// IP applies equality check predicate on the "ip" field. It's identical to IPEQ.
func IP(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldEQ(FieldIP, v))
}

// UserAgent applies equality check predicate on the "user_agent" field. It's identical to UserAgentEQ.
func UserAgent(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldEQ(FieldUserAgent, v))
}

// Detail applies equality check predicate on the "detail" field. It's identical to DetailEQ.
func Detail(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldEQ(FieldDetail, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldNotNull(FieldUpdatedAt))
}

// OrganizationIDEQ applies the EQ predicate on the "organization_id" field.
func OrganizationIDEQ(v uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldEQ(FieldOrganizationID, v))
}

// OrganizationIDNEQ applies the NEQ predicate on the "organization_id" field.
func OrganizationIDNEQ(v uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldNEQ(FieldOrganizationID, v))
}

// OrganizationIDIn applies the In predicate on the "organization_id" field.
func OrganizationIDIn(vs ...uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldIn(FieldOrganizationID, vs...))
}

// OrganizationIDNotIn applies the NotIn predicate on the "organization_id" field.
func OrganizationIDNotIn(vs ...uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldNotIn(FieldOrganizationID, vs...))
}

// OrganizationIDGT applies the GT predicate on the "organization_id" field.
func OrganizationIDGT(v uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldGT(FieldOrganizationID, v))
}

// OrganizationIDGTE applies the GTE predicate on the "organization_id" field.
func OrganizationIDGTE(v uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldGTE(FieldOrganizationID, v))
}

// OrganizationIDLT applies the LT predicate on the "organization_id" field.
func OrganizationIDLT(v uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldLT(FieldOrganizationID, v))
}

// OrganizationIDLTE applies the LTE predicate on the "organization_id" field.
func OrganizationIDLTE(v uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldLTE(FieldOrganizationID, v))
}

// OrganizationIDIsNil applies the IsNil predicate on the "organization_id" field.
func OrganizationIDIsNil() predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldIsNull(FieldOrganizationID))
}

// OrganizationIDNotNil applies the NotNil predicate on the "organization_id" field.
func OrganizationIDNotNil() predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldNotNull(FieldOrganizationID))
}

// ActorIDEQ applies the EQ predicate on the "actor_id" field.
func ActorIDEQ(v uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldEQ(FieldActorID, v))
}

// ActorIDNEQ applies the NEQ predicate on the "actor_id" field.
func ActorIDNEQ(v uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldNEQ(FieldActorID, v))
}

// ActorIDIn applies the In predicate on the "actor_id" field.
func ActorIDIn(vs ...uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldIn(FieldActorID, vs...))
}

// ActorIDNotIn applies the NotIn predicate on the "actor_id" field.
func ActorIDNotIn(vs ...uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldNotIn(FieldActorID, vs...))
}

// ActorIDGT applies the GT predicate on the "actor_id" field.
func ActorIDGT(v uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldGT(FieldActorID, v))
}

// ActorIDGTE applies the GTE predicate on the "actor_id" field.
func ActorIDGTE(v uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldGTE(FieldActorID, v))
}

// ActorIDLT applies the LT predicate on the "actor_id" field.
func ActorIDLT(v uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldLT(FieldActorID, v))
}

// ActorIDLTE applies the LTE predicate on the "actor_id" field.
func ActorIDLTE(v uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldLTE(FieldActorID, v))
}

// SubjectIDEQ applies the EQ predicate on the "subject_id" field.
func SubjectIDEQ(v uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldEQ(FieldSubjectID, v))
}

// SubjectIDNEQ applies the NEQ predicate on the "subject_id" field.
func SubjectIDNEQ(v uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldNEQ(FieldSubjectID, v))
}

// SubjectIDIn applies the In predicate on the "subject_id" field.
func SubjectIDIn(vs ...uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldIn(FieldSubjectID, vs...))
}

// SubjectIDNotIn applies the NotIn predicate on the "subject_id" field.
func SubjectIDNotIn(vs ...uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldNotIn(FieldSubjectID, vs...))
}

// SubjectIDGT applies the GT predicate on the "subject_id" field.
func SubjectIDGT(v uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldGT(FieldSubjectID, v))
}

// SubjectIDGTE applies the GTE predicate on the "subject_id" field.
func SubjectIDGTE(v uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldGTE(FieldSubjectID, v))
}

// SubjectIDLT applies the LT predicate on the "subject_id" field.
func SubjectIDLT(v uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldLT(FieldSubjectID, v))
}

// SubjectIDLTE applies the LTE predicate on the "subject_id" field.
func SubjectIDLTE(v uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldLTE(FieldSubjectID, v))
}

// SubjectIDIsNil applies the IsNil predicate on the "subject_id" field.
func SubjectIDIsNil() predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldIsNull(FieldSubjectID))
}

// SubjectIDNotNil applies the NotNil predicate on the "subject_id" field.
func SubjectIDNotNil() predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldNotNull(FieldSubjectID))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldNotIn(FieldAction, vs...))
}

// ActionGT applies the GT predicate on the "action" field.
func ActionGT(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldGT(FieldAction, v))
}

// ActionGTE applies the GTE predicate on the "action" field.
func ActionGTE(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldGTE(FieldAction, v))
}

// ActionLT applies the LT predicate on the "action" field.
func ActionLT(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldLT(FieldAction, v))
}

// ActionLTE applies the LTE predicate on the "action" field.
func ActionLTE(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldLTE(FieldAction, v))
}

// ActionContains applies the Contains predicate on the "action" field.
func ActionContains(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldContains(FieldAction, v))
}

// ActionHasPrefix applies the HasPrefix predicate on the "action" field.
func ActionHasPrefix(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldHasPrefix(FieldAction, v))
}

// ActionHasSuffix applies the HasSuffix predicate on the "action" field.
func ActionHasSuffix(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldHasSuffix(FieldAction, v))
}

// ActionEqualFold applies the EqualFold predicate on the "action" field.
func ActionEqualFold(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldEqualFold(FieldAction, v))
}

// ActionContainsFold applies the ContainsFold predicate on the "action" field.
func ActionContainsFold(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldContainsFold(FieldAction, v))
}

// RoleIDEQ applies the EQ predicate on the "role_id" field.
func RoleIDEQ(v uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldEQ(FieldRoleID, v))
}

// RoleIDNEQ applies the NEQ predicate on the "role_id" field.
func RoleIDNEQ(v uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldNEQ(FieldRoleID, v))
}

// RoleIDIn applies the In predicate on the "role_id" field.
func RoleIDIn(vs ...uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldIn(FieldRoleID, vs...))
}

// RoleIDNotIn applies the NotIn predicate on the "role_id" field.
func RoleIDNotIn(vs ...uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldNotIn(FieldRoleID, vs...))
}

// RoleIDGT applies the GT predicate on the "role_id" field.
func RoleIDGT(v uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldGT(FieldRoleID, v))
}

// RoleIDGTE applies the GTE predicate on the "role_id" field.
func RoleIDGTE(v uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldGTE(FieldRoleID, v))
}

// RoleIDLT applies the LT predicate on the "role_id" field.
func RoleIDLT(v uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldLT(FieldRoleID, v))
}

// RoleIDLTE applies the LTE predicate on the "role_id" field.
func RoleIDLTE(v uuid.UUID) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldLTE(FieldRoleID, v))
}

// RoleIDIsNil applies the IsNil predicate on the "role_id" field.
func RoleIDIsNil() predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldIsNull(FieldRoleID))
}

// RoleIDNotNil applies the NotNil predicate on the "role_id" field.
func RoleIDNotNil() predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldNotNull(FieldRoleID))
}

// PermissionKeyEQ applies the EQ predicate on the "permission_key" field.
func PermissionKeyEQ(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldEQ(FieldPermissionKey, v))
}

// PermissionKeyNEQ applies the NEQ predicate on the "permission_key" field.
func PermissionKeyNEQ(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldNEQ(FieldPermissionKey, v))
}

// PermissionKeyIn applies the In predicate on the "permission_key" field.
func PermissionKeyIn(vs ...string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldIn(FieldPermissionKey, vs...))
}

// PermissionKeyNotIn applies the NotIn predicate on the "permission_key" field.
func PermissionKeyNotIn(vs ...string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldNotIn(FieldPermissionKey, vs...))
}

// PermissionKeyGT applies the GT predicate on the "permission_key" field.
func PermissionKeyGT(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldGT(FieldPermissionKey, v))
}

// PermissionKeyGTE applies the GTE predicate on the "permission_key" field.
func PermissionKeyGTE(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldGTE(FieldPermissionKey, v))
}

// PermissionKeyLT applies the LT predicate on the "permission_key" field.
func PermissionKeyLT(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldLT(FieldPermissionKey, v))
}

// PermissionKeyLTE applies the LTE predicate on the "permission_key" field.
func PermissionKeyLTE(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldLTE(FieldPermissionKey, v))
}

// PermissionKeyContains applies the Contains predicate on the "permission_key" field.
func PermissionKeyContains(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldContains(FieldPermissionKey, v))
}

// PermissionKeyHasPrefix applies the HasPrefix predicate on the "permission_key" field.
func PermissionKeyHasPrefix(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldHasPrefix(FieldPermissionKey, v))
}

// PermissionKeyHasSuffix applies the HasSuffix predicate on the "permission_key" field.
func PermissionKeyHasSuffix(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldHasSuffix(FieldPermissionKey, v))
}

// PermissionKeyIsNil applies the IsNil predicate on the "permission_key" field.
func PermissionKeyIsNil() predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldIsNull(FieldPermissionKey))
}

// PermissionKeyNotNil applies the NotNil predicate on the "permission_key" field.
func PermissionKeyNotNil() predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldNotNull(FieldPermissionKey))
}

// PermissionKeyEqualFold applies the EqualFold predicate on the "permission_key" field.
func PermissionKeyEqualFold(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldEqualFold(FieldPermissionKey, v))
}

// PermissionKeyContainsFold applies the ContainsFold predicate on the "permission_key" field.
func PermissionKeyContainsFold(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldContainsFold(FieldPermissionKey, v))
}

// IPEQ applies the EQ predicate on the "ip" field.
func IPEQ(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldEQ(FieldIP, v))
}

// IPNEQ applies the NEQ predicate on the "ip" field.
func IPNEQ(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldNEQ(FieldIP, v))
}

// IPIn applies the In predicate on the "ip" field.
func IPIn(vs ...string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldIn(FieldIP, vs...))
}

// IPNotIn applies the NotIn predicate on the "ip" field.
func IPNotIn(vs ...string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldNotIn(FieldIP, vs...))
}

// IPGT applies the GT predicate on the "ip" field.
func IPGT(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldGT(FieldIP, v))
}

// IPGTE applies the GTE predicate on the "ip" field.
func IPGTE(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldGTE(FieldIP, v))
}

// IPLT applies the LT predicate on the "ip" field.
func IPLT(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldLT(FieldIP, v))
}

// IPLTE applies the LTE predicate on the "ip" field.
func IPLTE(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldLTE(FieldIP, v))
}

// IPContains applies the Contains predicate on the "ip" field.
func IPContains(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldContains(FieldIP, v))
}

// IPHasPrefix applies the HasPrefix predicate on the "ip" field.
func IPHasPrefix(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldHasPrefix(FieldIP, v))
}

// IPHasSuffix applies the HasSuffix predicate on the "ip" field.
func IPHasSuffix(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldHasSuffix(FieldIP, v))
}

// IPEqualFold applies the EqualFold predicate on the "ip" field.
func IPEqualFold(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldEqualFold(FieldIP, v))
}

// IPContainsFold applies the ContainsFold predicate on the "ip" field.
func IPContainsFold(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldContainsFold(FieldIP, v))
}

// UserAgentEQ applies the EQ predicate on the "user_agent" field.
func UserAgentEQ(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldEQ(FieldUserAgent, v))
}

// UserAgentNEQ applies the NEQ predicate on the "user_agent" field.
func UserAgentNEQ(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldNEQ(FieldUserAgent, v))
}

// UserAgentIn applies the In predicate on the "user_agent" field.
func UserAgentIn(vs ...string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldIn(FieldUserAgent, vs...))
}

// UserAgentNotIn applies the NotIn predicate on the "user_agent" field.
func UserAgentNotIn(vs ...string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldNotIn(FieldUserAgent, vs...))
}

// UserAgentGT applies the GT predicate on the "user_agent" field.
func UserAgentGT(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldGT(FieldUserAgent, v))
}

// UserAgentGTE applies the GTE predicate on the "user_agent" field.
func UserAgentGTE(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldGTE(FieldUserAgent, v))
}

// UserAgentLT applies the LT predicate on the "user_agent" field.
func UserAgentLT(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldLT(FieldUserAgent, v))
}

// UserAgentLTE applies the LTE predicate on the "user_agent" field.
func UserAgentLTE(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldLTE(FieldUserAgent, v))
}

// UserAgentContains applies the Contains predicate on the "user_agent" field.
func UserAgentContains(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldContains(FieldUserAgent, v))
}

// UserAgentHasPrefix applies the HasPrefix predicate on the "user_agent" field.
func UserAgentHasPrefix(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldHasPrefix(FieldUserAgent, v))
}

// UserAgentHasSuffix applies the HasSuffix predicate on the "user_agent" field.
func UserAgentHasSuffix(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldHasSuffix(FieldUserAgent, v))
}

// UserAgentIsNil applies the IsNil predicate on the "user_agent" field.
func UserAgentIsNil() predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldIsNull(FieldUserAgent))
}

// UserAgentNotNil applies the NotNil predicate on the "user_agent" field.
func UserAgentNotNil() predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldNotNull(FieldUserAgent))
}

// UserAgentEqualFold applies the EqualFold predicate on the "user_agent" field.
func UserAgentEqualFold(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldEqualFold(FieldUserAgent, v))
}

// UserAgentContainsFold applies the ContainsFold predicate on the "user_agent" field.
func UserAgentContainsFold(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldContainsFold(FieldUserAgent, v))
}

// DetailEQ applies the EQ predicate on the "detail" field.
func DetailEQ(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldEQ(FieldDetail, v))
}

// DetailNEQ applies the NEQ predicate on the "detail" field.
func DetailNEQ(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldNEQ(FieldDetail, v))
}

// DetailIn applies the In predicate on the "detail" field.
func DetailIn(vs ...string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldIn(FieldDetail, vs...))
}

// DetailNotIn applies the NotIn predicate on the "detail" field.
func DetailNotIn(vs ...string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldNotIn(FieldDetail, vs...))
}

// DetailGT applies the GT predicate on the "detail" field.
func DetailGT(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldGT(FieldDetail, v))
}

// DetailGTE applies the GTE predicate on the "detail" field.
func DetailGTE(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldGTE(FieldDetail, v))
}

// DetailLT applies the LT predicate on the "detail" field.
func DetailLT(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldLT(FieldDetail, v))
}

// DetailLTE applies the LTE predicate on the "detail" field.
func DetailLTE(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldLTE(FieldDetail, v))
}

// DetailContains applies the Contains predicate on the "detail" field.
func DetailContains(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldContains(FieldDetail, v))
}

// DetailHasPrefix applies the HasPrefix predicate on the "detail" field.
func DetailHasPrefix(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldHasPrefix(FieldDetail, v))
}

// DetailHasSuffix applies the HasSuffix predicate on the "detail" field.
func DetailHasSuffix(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldHasSuffix(FieldDetail, v))
}

// DetailIsNil applies the IsNil predicate on the "detail" field.
func DetailIsNil() predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldIsNull(FieldDetail))
}

// DetailNotNil applies the NotNil predicate on the "detail" field.
func DetailNotNil() predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldNotNull(FieldDetail))
}

// DetailEqualFold applies the EqualFold predicate on the "detail" field.
func DetailEqualFold(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldEqualFold(FieldDetail, v))
}

// DetailContainsFold applies the ContainsFold predicate on the "detail" field.
func DetailContainsFold(v string) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.FieldContainsFold(FieldDetail, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AuthzEvent) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AuthzEvent) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AuthzEvent) predicate.AuthzEvent {
	return predicate.AuthzEvent(sql.NotPredicates(p))
}
