// Code generated by ent, DO NOT EDIT.

package intercept

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/authzevent"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/device"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/emailchange"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/invitation"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/invitationrole"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/loginevent"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/membership"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/membershiprole"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/organization"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/passwordreset"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/predicate"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/role"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/rolepermission"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/twofactorchallenge"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/user"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/usersystemrole"
)

// The Query interface represents an operation that queries a graph.
// By using this interface, users can write generic code that manipulates
// query builders of different types.
type Query interface {
	// Type returns the string representation of the query type.
	Type() string
	// Limit the number of records to be returned by this query.
	Limit(int)
	// Offset to start from.
	Offset(int)
	// Unique configures the query builder to filter duplicate records.
	Unique(bool)
	// Order specifies how the records should be ordered.
	Order(...func(*sql.Selector))
	// WhereP appends storage-level predicates to the query builder. Using this method, users
	// can use type-assertion to append predicates that do not depend on any generated package.
	WhereP(...func(*sql.Selector))
}

// The Func type is an adapter that allows ordinary functions to be used as interceptors.
// Unlike traversal functions, interceptors are skipped during graph traversals. Note that the
// implementation of Func is different from the one defined in entgo.io/ent.InterceptFunc.
type Func func(context.Context, Query) error

// Intercept calls f(ctx, q) and then applied the next Querier.
func (f Func) Intercept(next ent.Querier) ent.Querier {
	return ent.QuerierFunc(func(ctx context.Context, q ent.Query) (ent.Value, error) {
		query, err := NewQuery(q)
		if err != nil {
			return nil, err
		}
		if err := f(ctx, query); err != nil {
			return nil, err
		}
		return next.Query(ctx, q)
	})
}

// The TraverseFunc type is an adapter to allow the use of ordinary function as Traverser.
// If f is a function with the appropriate signature, TraverseFunc(f) is a Traverser that calls f.
type TraverseFunc func(context.Context, Query) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseFunc) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseFunc) Traverse(ctx context.Context, q ent.Query) error {
	query, err := NewQuery(q)
	if err != nil {
		return err
	}
	return f(ctx, query)
}

// The AuthzEventFunc type is an adapter to allow the use of ordinary function as a Querier.
type AuthzEventFunc func(context.Context, *ent.AuthzEventQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f AuthzEventFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.AuthzEventQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.AuthzEventQuery", q)
}

// The TraverseAuthzEvent type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAuthzEvent func(context.Context, *ent.AuthzEventQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAuthzEvent) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAuthzEvent) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.AuthzEventQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.AuthzEventQuery", q)
}

// The DeviceFunc type is an adapter to allow the use of ordinary function as a Querier.
type DeviceFunc func(context.Context, *ent.DeviceQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f DeviceFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.DeviceQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.DeviceQuery", q)
}

// The TraverseDevice type is an adapter to allow the use of ordinary function as Traverser.
type TraverseDevice func(context.Context, *ent.DeviceQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseDevice) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseDevice) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.DeviceQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.DeviceQuery", q)
}

// The EmailChangeFunc type is an adapter to allow the use of ordinary function as a Querier.
type EmailChangeFunc func(context.Context, *ent.EmailChangeQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f EmailChangeFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.EmailChangeQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.EmailChangeQuery", q)
}

// The TraverseEmailChange type is an adapter to allow the use of ordinary function as Traverser.
type TraverseEmailChange func(context.Context, *ent.EmailChangeQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseEmailChange) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseEmailChange) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.EmailChangeQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.EmailChangeQuery", q)
}

// The InvitationFunc type is an adapter to allow the use of ordinary function as a Querier.
type InvitationFunc func(context.Context, *ent.InvitationQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f InvitationFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.InvitationQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.InvitationQuery", q)
}

// The TraverseInvitation type is an adapter to allow the use of ordinary function as Traverser.
type TraverseInvitation func(context.Context, *ent.InvitationQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseInvitation) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseInvitation) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.InvitationQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.InvitationQuery", q)
}

// The InvitationRoleFunc type is an adapter to allow the use of ordinary function as a Querier.
type InvitationRoleFunc func(context.Context, *ent.InvitationRoleQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f InvitationRoleFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.InvitationRoleQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.InvitationRoleQuery", q)
}

// The TraverseInvitationRole type is an adapter to allow the use of ordinary function as Traverser.
type TraverseInvitationRole func(context.Context, *ent.InvitationRoleQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseInvitationRole) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseInvitationRole) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.InvitationRoleQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.InvitationRoleQuery", q)
}

// The LoginEventFunc type is an adapter to allow the use of ordinary function as a Querier.
type LoginEventFunc func(context.Context, *ent.LoginEventQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f LoginEventFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.LoginEventQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.LoginEventQuery", q)
}

// The TraverseLoginEvent type is an adapter to allow the use of ordinary function as Traverser.
type TraverseLoginEvent func(context.Context, *ent.LoginEventQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseLoginEvent) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseLoginEvent) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.LoginEventQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.LoginEventQuery", q)
}

// The MembershipFunc type is an adapter to allow the use of ordinary function as a Querier.
type MembershipFunc func(context.Context, *ent.MembershipQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f MembershipFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.MembershipQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.MembershipQuery", q)
}

// The TraverseMembership type is an adapter to allow the use of ordinary function as Traverser.
type TraverseMembership func(context.Context, *ent.MembershipQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseMembership) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseMembership) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.MembershipQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.MembershipQuery", q)
}

// The MembershipRoleFunc type is an adapter to allow the use of ordinary function as a Querier.
type MembershipRoleFunc func(context.Context, *ent.MembershipRoleQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f MembershipRoleFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.MembershipRoleQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.MembershipRoleQuery", q)
}

// The TraverseMembershipRole type is an adapter to allow the use of ordinary function as Traverser.
type TraverseMembershipRole func(context.Context, *ent.MembershipRoleQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseMembershipRole) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseMembershipRole) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.MembershipRoleQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.MembershipRoleQuery", q)
}

// The OrganizationFunc type is an adapter to allow the use of ordinary function as a Querier.
type OrganizationFunc func(context.Context, *ent.OrganizationQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f OrganizationFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.OrganizationQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.OrganizationQuery", q)
}

// The TraverseOrganization type is an adapter to allow the use of ordinary function as Traverser.
type TraverseOrganization func(context.Context, *ent.OrganizationQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseOrganization) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseOrganization) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.OrganizationQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.OrganizationQuery", q)
}

// The PasswordResetFunc type is an adapter to allow the use of ordinary function as a Querier.
type PasswordResetFunc func(context.Context, *ent.PasswordResetQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f PasswordResetFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.PasswordResetQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.PasswordResetQuery", q)
}

// The TraversePasswordReset type is an adapter to allow the use of ordinary function as Traverser.
type TraversePasswordReset func(context.Context, *ent.PasswordResetQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraversePasswordReset) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraversePasswordReset) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.PasswordResetQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.PasswordResetQuery", q)
}

// The RoleFunc type is an adapter to allow the use of ordinary function as a Querier.
type RoleFunc func(context.Context, *ent.RoleQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f RoleFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.RoleQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.RoleQuery", q)
}

// The TraverseRole type is an adapter to allow the use of ordinary function as Traverser.
type TraverseRole func(context.Context, *ent.RoleQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseRole) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseRole) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.RoleQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.RoleQuery", q)
}

// The RolePermissionFunc type is an adapter to allow the use of ordinary function as a Querier.
type RolePermissionFunc func(context.Context, *ent.RolePermissionQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f RolePermissionFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.RolePermissionQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.RolePermissionQuery", q)
}

// The TraverseRolePermission type is an adapter to allow the use of ordinary function as Traverser.
type TraverseRolePermission func(context.Context, *ent.RolePermissionQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseRolePermission) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseRolePermission) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.RolePermissionQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.RolePermissionQuery", q)
}

// The TwoFactorChallengeFunc type is an adapter to allow the use of ordinary function as a Querier.
type TwoFactorChallengeFunc func(context.Context, *ent.TwoFactorChallengeQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f TwoFactorChallengeFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.TwoFactorChallengeQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.TwoFactorChallengeQuery", q)
}

// The TraverseTwoFactorChallenge type is an adapter to allow the use of ordinary function as Traverser.
type TraverseTwoFactorChallenge func(context.Context, *ent.TwoFactorChallengeQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseTwoFactorChallenge) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseTwoFactorChallenge) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.TwoFactorChallengeQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.TwoFactorChallengeQuery", q)
}

// The UserFunc type is an adapter to allow the use of ordinary function as a Querier.
type UserFunc func(context.Context, *ent.UserQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UserFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UserQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UserQuery", q)
}

// The TraverseUser type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUser func(context.Context, *ent.UserQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUser) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUser) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UserQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UserQuery", q)
}

// The UserSystemRoleFunc type is an adapter to allow the use of ordinary function as a Querier.
type UserSystemRoleFunc func(context.Context, *ent.UserSystemRoleQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UserSystemRoleFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UserSystemRoleQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UserSystemRoleQuery", q)
}

// The TraverseUserSystemRole type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUserSystemRole func(context.Context, *ent.UserSystemRoleQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUserSystemRole) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUserSystemRole) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UserSystemRoleQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UserSystemRoleQuery", q)
}

// NewQuery returns the generic Query interface for the given typed query.
func NewQuery(q ent.Query) (Query, error) {
	switch q := q.(type) {
	case *ent.AuthzEventQuery:
		return &query[*ent.AuthzEventQuery, predicate.AuthzEvent, authzevent.OrderOption]{typ: ent.TypeAuthzEvent, tq: q}, nil
	case *ent.DeviceQuery:
		return &query[*ent.DeviceQuery, predicate.Device, device.OrderOption]{typ: ent.TypeDevice, tq: q}, nil
	case *ent.EmailChangeQuery:
		return &query[*ent.EmailChangeQuery, predicate.EmailChange, emailchange.OrderOption]{typ: ent.TypeEmailChange, tq: q}, nil
	case *ent.InvitationQuery:
		return &query[*ent.InvitationQuery, predicate.Invitation, invitation.OrderOption]{typ: ent.TypeInvitation, tq: q}, nil
	case *ent.InvitationRoleQuery:
		return &query[*ent.InvitationRoleQuery, predicate.InvitationRole, invitationrole.OrderOption]{typ: ent.TypeInvitationRole, tq: q}, nil
	case *ent.LoginEventQuery:
		return &query[*ent.LoginEventQuery, predicate.LoginEvent, loginevent.OrderOption]{typ: ent.TypeLoginEvent, tq: q}, nil
	case *ent.MembershipQuery:
		return &query[*ent.MembershipQuery, predicate.Membership, membership.OrderOption]{typ: ent.TypeMembership, tq: q}, nil
	case *ent.MembershipRoleQuery:
		return &query[*ent.MembershipRoleQuery, predicate.MembershipRole, membershiprole.OrderOption]{typ: ent.TypeMembershipRole, tq: q}, nil
	case *ent.OrganizationQuery:
		return &query[*ent.OrganizationQuery, predicate.Organization, organization.OrderOption]{typ: ent.TypeOrganization, tq: q}, nil
	case *ent.PasswordResetQuery:
		return &query[*ent.PasswordResetQuery, predicate.PasswordReset, passwordreset.OrderOption]{typ: ent.TypePasswordReset, tq: q}, nil
	case *ent.RoleQuery:
		return &query[*ent.RoleQuery, predicate.Role, role.OrderOption]{typ: ent.TypeRole, tq: q}, nil
	case *ent.RolePermissionQuery:
		return &query[*ent.RolePermissionQuery, predicate.RolePermission, rolepermission.OrderOption]{typ: ent.TypeRolePermission, tq: q}, nil
	case *ent.TwoFactorChallengeQuery:
		return &query[*ent.TwoFactorChallengeQuery, predicate.TwoFactorChallenge, twofactorchallenge.OrderOption]{typ: ent.TypeTwoFactorChallenge, tq: q}, nil
	case *ent.UserQuery:
		return &query[*ent.UserQuery, predicate.User, user.OrderOption]{typ: ent.TypeUser, tq: q}, nil
	case *ent.UserSystemRoleQuery:
		return &query[*ent.UserSystemRoleQuery, predicate.UserSystemRole, usersystemrole.OrderOption]{typ: ent.TypeUserSystemRole, tq: q}, nil
	default:
		return nil, fmt.Errorf("unknown query type %T", q)
	}
}

type query[T any, P ~func(*sql.Selector), R ~func(*sql.Selector)] struct {
	typ string
	tq  interface {
		Limit(int) T
		Offset(int) T
		Unique(bool) T
		Order(...R) T
		Where(...P) T
	}
}

func (q query[T, P, R]) Type() string {
	return q.typ
}

func (q query[T, P, R]) Limit(limit int) {
	q.tq.Limit(limit)
}

func (q query[T, P, R]) Offset(offset int) {
	q.tq.Offset(offset)
}

func (q query[T, P, R]) Unique(unique bool) {
	q.tq.Unique(unique)
}

func (q query[T, P, R]) Order(orders ...func(*sql.Selector)) {
	rs := make([]R, len(orders))
	for i := range orders {
		rs[i] = orders[i]
	}
	q.tq.Order(rs...)
}

func (q query[T, P, R]) WhereP(ps ...func(*sql.Selector)) {
	p := make([]P, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	q.tq.Where(p...)
}
