// Code generated by ent, DO NOT EDIT.

package usersystemrole

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/wokacz/multi-tenant-go-service/internal/store/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldEQ(FieldUserID, v))
}

// RoleKey applies equality check predicate on the "role_key" field. It's identical to RoleKeyEQ.
func RoleKey(v string) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldEQ(FieldRoleKey, v))
}

// GrantedBy applies equality check predicate on the "granted_by" field. It's identical to GrantedByEQ.
func GrantedBy(v uuid.UUID) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldEQ(FieldGrantedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldNotIn(FieldUserID, vs...))
}

// RoleKeyEQ applies the EQ predicate on the "role_key" field.
func RoleKeyEQ(v string) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldEQ(FieldRoleKey, v))
}

// RoleKeyNEQ applies the NEQ predicate on the "role_key" field.
func RoleKeyNEQ(v string) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldNEQ(FieldRoleKey, v))
}

// RoleKeyIn applies the In predicate on the "role_key" field.
func RoleKeyIn(vs ...string) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldIn(FieldRoleKey, vs...))
}

// RoleKeyNotIn applies the NotIn predicate on the "role_key" field.
func RoleKeyNotIn(vs ...string) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldNotIn(FieldRoleKey, vs...))
}

// RoleKeyGT applies the GT predicate on the "role_key" field.
func RoleKeyGT(v string) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldGT(FieldRoleKey, v))
}

// RoleKeyGTE applies the GTE predicate on the "role_key" field.
func RoleKeyGTE(v string) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldGTE(FieldRoleKey, v))
}

// RoleKeyLT applies the LT predicate on the "role_key" field.
func RoleKeyLT(v string) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldLT(FieldRoleKey, v))
}

// RoleKeyLTE applies the LTE predicate on the "role_key" field.
func RoleKeyLTE(v string) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldLTE(FieldRoleKey, v))
}

// RoleKeyContains applies the Contains predicate on the "role_key" field.
func RoleKeyContains(v string) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldContains(FieldRoleKey, v))
}

// RoleKeyHasPrefix applies the HasPrefix predicate on the "role_key" field.
func RoleKeyHasPrefix(v string) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldHasPrefix(FieldRoleKey, v))
}

// RoleKeyHasSuffix applies the HasSuffix predicate on the "role_key" field.
func RoleKeyHasSuffix(v string) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldHasSuffix(FieldRoleKey, v))
}

// RoleKeyEqualFold applies the EqualFold predicate on the "role_key" field.
func RoleKeyEqualFold(v string) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldEqualFold(FieldRoleKey, v))
}

// RoleKeyContainsFold applies the ContainsFold predicate on the "role_key" field.
func RoleKeyContainsFold(v string) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldContainsFold(FieldRoleKey, v))
}

// GrantedByEQ applies the EQ predicate on the "granted_by" field.
func GrantedByEQ(v uuid.UUID) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldEQ(FieldGrantedBy, v))
}

// GrantedByNEQ applies the NEQ predicate on the "granted_by" field.
func GrantedByNEQ(v uuid.UUID) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldNEQ(FieldGrantedBy, v))
}

// GrantedByIn applies the In predicate on the "granted_by" field.
func GrantedByIn(vs ...uuid.UUID) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldIn(FieldGrantedBy, vs...))
}

// GrantedByNotIn applies the NotIn predicate on the "granted_by" field.
func GrantedByNotIn(vs ...uuid.UUID) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldNotIn(FieldGrantedBy, vs...))
}

// GrantedByGT applies the GT predicate on the "granted_by" field.
func GrantedByGT(v uuid.UUID) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldGT(FieldGrantedBy, v))
}

// GrantedByGTE applies the GTE predicate on the "granted_by" field.
func GrantedByGTE(v uuid.UUID) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldGTE(FieldGrantedBy, v))
}

// GrantedByLT applies the LT predicate on the "granted_by" field.
func GrantedByLT(v uuid.UUID) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldLT(FieldGrantedBy, v))
}

// GrantedByLTE applies the LTE predicate on the "granted_by" field.
func GrantedByLTE(v uuid.UUID) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldLTE(FieldGrantedBy, v))
}

// GrantedByIsNil applies the IsNil predicate on the "granted_by" field.
func GrantedByIsNil() predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldIsNull(FieldGrantedBy))
}

// GrantedByNotNil applies the NotNil predicate on the "granted_by" field.
func GrantedByNotNil() predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.FieldNotNull(FieldGrantedBy))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserSystemRole {
	return predicate.UserSystemRole(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserSystemRole {
	return predicate.UserSystemRole(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserSystemRole) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserSystemRole) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserSystemRole) predicate.UserSystemRole {
	return predicate.UserSystemRole(sql.NotPredicates(p))
}
