// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
 * Generated by ng-openapi
 * Generated Angular service for Organizations controller
 * Do not edit this file manually
 */
import {
  HttpClient,
  HttpContext,
  HttpContextToken,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse,
} from '@angular/common/http';
import { inject, Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from '../tokens';
import { HttpParamsBuilder } from '../utils/http-params-builder';
import {
  RequestOptions,
  ListMyOrganizationsOutputBody,
  PermissionSnapshotResponse,
  OrganizationResponse,
  UpdateOrganizationRequest,
  ListAuditOutputBody,
  ListMembersOutputBody,
  AddMemberRequest,
  MemberResponse,
  UpdateMemberStatusRequest,
  SetMemberRolesRequest,
  ListRolesOutputBody,
  CreateRoleRequest,
  RoleResponse,
  UpdateRoleRequest,
  SetRolePermissionsRequest,
  ListPermissionsOutputBody,
} from '../models';

@Injectable({ providedIn: 'root' })
export class OrganizationsService {
  private readonly httpClient: HttpClient = inject(HttpClient);
  private readonly basePath: string = inject(BASE_PATH_DEFAULT);
  private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

  private createContextWithClientId(existingContext?: HttpContext): HttpContext {
    const context = existingContext || new HttpContext();
    return context.set(this.clientContextToken, 'default');
  }

  listMyOrganizations(
    observe?: 'body',
    options?: RequestOptions<'json'>,
  ): Observable<ListMyOrganizationsOutputBody>;
  listMyOrganizations(
    observe?: 'response',
    options?: RequestOptions<'json'>,
  ): Observable<HttpResponse<ListMyOrganizationsOutputBody>>;
  listMyOrganizations(
    observe?: 'events',
    options?: RequestOptions<'json'>,
  ): Observable<HttpEvent<ListMyOrganizationsOutputBody>>;
  /** Returns every organization the account belongs to, including the ones it has only been invited to and the ones it is suspended in, so a client can tell those apart. Self-service: no permission is required, and none can take it away. */
  listMyOrganizations(
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/v1/me/organizations`;

    let headers: HttpHeaders;
    if (options?.headers instanceof HttpHeaders) {
      headers = options.headers;
    } else {
      headers = new HttpHeaders(options?.headers);
    }
    // Advertise the response content type declared in the spec
    if (!headers.has('Accept')) {
      headers = headers.set('Accept', 'application/json');
    }

    return this.httpClient.request('get', url, {
      observe,
      headers,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    });
  }

  getMyPermissions(
    observe?: 'body',
    options?: RequestOptions<'json'>,
  ): Observable<PermissionSnapshotResponse>;
  getMyPermissions(
    observe?: 'response',
    options?: RequestOptions<'json'>,
  ): Observable<HttpResponse<PermissionSnapshotResponse>>;
  getMyPermissions(
    observe?: 'events',
    options?: RequestOptions<'json'>,
  ): Observable<HttpEvent<PermissionSnapshotResponse>>;
  /** The snapshot a client uses to decide what to render. Self-service: no permission is required and none can take it away. It is a hint, not a decision — every request is authorized again on the server, so a client holding a stale snapshot receives a 403 and should refresh. Carries an ETag; send it back as If-None-Match to get a 304. */
  getMyPermissions(
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/v1/me/permissions`;

    let headers: HttpHeaders;
    if (options?.headers instanceof HttpHeaders) {
      headers = options.headers;
    } else {
      headers = new HttpHeaders(options?.headers);
    }
    // Advertise the response content type declared in the spec
    if (!headers.has('Accept')) {
      headers = headers.set('Accept', 'application/json');
    }

    return this.httpClient.request('get', url, {
      observe,
      headers,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    });
  }

  getOrganization(
    orgID: string,
    observe?: 'body',
    options?: RequestOptions<'json'>,
  ): Observable<OrganizationResponse>;
  getOrganization(
    orgID: string,
    observe?: 'response',
    options?: RequestOptions<'json'>,
  ): Observable<HttpResponse<OrganizationResponse>>;
  getOrganization(
    orgID: string,
    observe?: 'events',
    options?: RequestOptions<'json'>,
  ): Observable<HttpEvent<OrganizationResponse>>;
  /** Requires organization.read in the organization named in the path. A caller with no active membership gets 404 rather than 403: whether an organization exists is not something a stranger may find out by trying identifiers. */
  getOrganization(
    orgID: string,
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/v1/orgs/${orgID}`;

    let headers: HttpHeaders;
    if (options?.headers instanceof HttpHeaders) {
      headers = options.headers;
    } else {
      headers = new HttpHeaders(options?.headers);
    }
    // Advertise the response content type declared in the spec
    if (!headers.has('Accept')) {
      headers = headers.set('Accept', 'application/json');
    }

    return this.httpClient.request('get', url, {
      observe,
      headers,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    });
  }

  updateOrganization(
    orgID: string,
    updateOrganizationRequest: UpdateOrganizationRequest,
    observe?: 'body',
    options?: RequestOptions<'json'>,
  ): Observable<OrganizationResponse>;
  updateOrganization(
    orgID: string,
    updateOrganizationRequest: UpdateOrganizationRequest,
    observe?: 'response',
    options?: RequestOptions<'json'>,
  ): Observable<HttpResponse<OrganizationResponse>>;
  updateOrganization(
    orgID: string,
    updateOrganizationRequest: UpdateOrganizationRequest,
    observe?: 'events',
    options?: RequestOptions<'json'>,
  ): Observable<HttpEvent<OrganizationResponse>>;
  /** Requires organization.update. The slug is not editable: it appears in links people have already shared. */
  updateOrganization(
    orgID: string,
    updateOrganizationRequest: UpdateOrganizationRequest,
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/v1/orgs/${orgID}`;

    let headers: HttpHeaders;
    if (options?.headers instanceof HttpHeaders) {
      headers = options.headers;
    } else {
      headers = new HttpHeaders(options?.headers);
    }
    // Advertise the response content type declared in the spec
    if (!headers.has('Accept')) {
      headers = headers.set('Accept', 'application/json');
    }
    // Set Content-Type for JSON requests if not already set
    if (!headers.has('Content-Type')) {
      headers = headers.set('Content-Type', 'application/json');
    }

    return this.httpClient.request('patch', url, {
      body: updateOrganizationRequest,
      observe,
      headers,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    });
  }

  deleteOrganization(
    orgID: string,
    observe?: 'body',
    options?: RequestOptions<'json'>,
  ): Observable<any>;
  deleteOrganization(
    orgID: string,
    observe?: 'response',
    options?: RequestOptions<'json'>,
  ): Observable<HttpResponse<any>>;
  deleteOrganization(
    orgID: string,
    observe?: 'events',
    options?: RequestOptions<'json'>,
  ): Observable<HttpEvent<any>>;
  /** Requires organization.delete. The default organization is protected and is refused with 409 — an installation that lost its only organization has no working accounts and no screen to undo it from. */
  deleteOrganization(
    orgID: string,
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/v1/orgs/${orgID}`;

    let headers: HttpHeaders;
    if (options?.headers instanceof HttpHeaders) {
      headers = options.headers;
    } else {
      headers = new HttpHeaders(options?.headers);
    }

    return this.httpClient.request('delete', url, {
      observe,
      headers,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    });
  }

  listAuditEvents(
    orgID: string,
    limit?: number,
    offset?: number,
    observe?: 'body',
    options?: RequestOptions<'json'>,
  ): Observable<ListAuditOutputBody>;
  listAuditEvents(
    orgID: string,
    limit?: number,
    offset?: number,
    observe?: 'response',
    options?: RequestOptions<'json'>,
  ): Observable<HttpResponse<ListAuditOutputBody>>;
  listAuditEvents(
    orgID: string,
    limit?: number,
    offset?: number,
    observe?: 'events',
    options?: RequestOptions<'json'>,
  ): Observable<HttpEvent<ListAuditOutputBody>>;
  /** Who granted or revoked what, and when. Requires audit.read. Entries are written in the same transaction as the change they describe, so the log cannot disagree with the state. */
  listAuditEvents(
    orgID: string,
    limit?: number,
    offset?: number,
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/v1/orgs/${orgID}/audit`;

    let params = new HttpParams();
    if (limit != null) {
      params = HttpParamsBuilder.addToHttpParams(params, limit, 'limit');
    }
    if (offset != null) {
      params = HttpParamsBuilder.addToHttpParams(params, offset, 'offset');
    }

    let headers: HttpHeaders;
    if (options?.headers instanceof HttpHeaders) {
      headers = options.headers;
    } else {
      headers = new HttpHeaders(options?.headers);
    }
    // Advertise the response content type declared in the spec
    if (!headers.has('Accept')) {
      headers = headers.set('Accept', 'application/json');
    }

    return this.httpClient.request('get', url, {
      observe,
      headers,
      params,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    });
  }

  listMembers(
    orgID: string,
    observe?: 'body',
    options?: RequestOptions<'json'>,
  ): Observable<ListMembersOutputBody>;
  listMembers(
    orgID: string,
    observe?: 'response',
    options?: RequestOptions<'json'>,
  ): Observable<HttpResponse<ListMembersOutputBody>>;
  listMembers(
    orgID: string,
    observe?: 'events',
    options?: RequestOptions<'json'>,
  ): Observable<HttpEvent<ListMembersOutputBody>>;
  /** Everyone in the organization, including invitations and suspensions, with the roles each holds. Requires members.read. */
  listMembers(
    orgID: string,
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/v1/orgs/${orgID}/members`;

    let headers: HttpHeaders;
    if (options?.headers instanceof HttpHeaders) {
      headers = options.headers;
    } else {
      headers = new HttpHeaders(options?.headers);
    }
    // Advertise the response content type declared in the spec
    if (!headers.has('Accept')) {
      headers = headers.set('Accept', 'application/json');
    }

    return this.httpClient.request('get', url, {
      observe,
      headers,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    });
  }

  addMember(
    orgID: string,
    addMemberRequest: AddMemberRequest,
    observe?: 'body',
    options?: RequestOptions<'json'>,
  ): Observable<MemberResponse>;
  addMember(
    orgID: string,
    addMemberRequest: AddMemberRequest,
    observe?: 'response',
    options?: RequestOptions<'json'>,
  ): Observable<HttpResponse<MemberResponse>>;
  addMember(
    orgID: string,
    addMemberRequest: AddMemberRequest,
    observe?: 'events',
    options?: RequestOptions<'json'>,
  ): Observable<HttpEvent<MemberResponse>>;
  /** Puts an existing account into the organization with the given roles. Requires members.invite, and every role named must be one the caller could grant themselves — otherwise this endpoint would be a way to acquire permissions the caller does not have. */
  addMember(
    orgID: string,
    addMemberRequest: AddMemberRequest,
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/v1/orgs/${orgID}/members`;

    let headers: HttpHeaders;
    if (options?.headers instanceof HttpHeaders) {
      headers = options.headers;
    } else {
      headers = new HttpHeaders(options?.headers);
    }
    // Advertise the response content type declared in the spec
    if (!headers.has('Accept')) {
      headers = headers.set('Accept', 'application/json');
    }
    // Set Content-Type for JSON requests if not already set
    if (!headers.has('Content-Type')) {
      headers = headers.set('Content-Type', 'application/json');
    }

    return this.httpClient.request('post', url, {
      body: addMemberRequest,
      observe,
      headers,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    });
  }

  updateMemberStatus(
    orgID: string,
    memberID: string,
    updateMemberStatusRequest: UpdateMemberStatusRequest,
    observe?: 'body',
    options?: RequestOptions<'json'>,
  ): Observable<MemberResponse>;
  updateMemberStatus(
    orgID: string,
    memberID: string,
    updateMemberStatusRequest: UpdateMemberStatusRequest,
    observe?: 'response',
    options?: RequestOptions<'json'>,
  ): Observable<HttpResponse<MemberResponse>>;
  updateMemberStatus(
    orgID: string,
    memberID: string,
    updateMemberStatusRequest: UpdateMemberStatusRequest,
    observe?: 'events',
    options?: RequestOptions<'json'>,
  ): Observable<HttpEvent<MemberResponse>>;
  /** Suspending withdraws every permission immediately, on tokens already issued, while keeping the role assignments so reinstating restores exactly what they had. Requires members.suspend. Suspending the last owner is refused with 409. */
  updateMemberStatus(
    orgID: string,
    memberID: string,
    updateMemberStatusRequest: UpdateMemberStatusRequest,
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/v1/orgs/${orgID}/members/${memberID}`;

    let headers: HttpHeaders;
    if (options?.headers instanceof HttpHeaders) {
      headers = options.headers;
    } else {
      headers = new HttpHeaders(options?.headers);
    }
    // Advertise the response content type declared in the spec
    if (!headers.has('Accept')) {
      headers = headers.set('Accept', 'application/json');
    }
    // Set Content-Type for JSON requests if not already set
    if (!headers.has('Content-Type')) {
      headers = headers.set('Content-Type', 'application/json');
    }

    return this.httpClient.request('patch', url, {
      body: updateMemberStatusRequest,
      observe,
      headers,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    });
  }

  removeMember(
    orgID: string,
    memberID: string,
    observe?: 'body',
    options?: RequestOptions<'json'>,
  ): Observable<any>;
  removeMember(
    orgID: string,
    memberID: string,
    observe?: 'response',
    options?: RequestOptions<'json'>,
  ): Observable<HttpResponse<any>>;
  removeMember(
    orgID: string,
    memberID: string,
    observe?: 'events',
    options?: RequestOptions<'json'>,
  ): Observable<HttpEvent<any>>;
  /** Deletes the membership and its role assignments. Requires members.remove. Removing the last owner is refused with 409. */
  removeMember(
    orgID: string,
    memberID: string,
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/v1/orgs/${orgID}/members/${memberID}`;

    let headers: HttpHeaders;
    if (options?.headers instanceof HttpHeaders) {
      headers = options.headers;
    } else {
      headers = new HttpHeaders(options?.headers);
    }

    return this.httpClient.request('delete', url, {
      observe,
      headers,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    });
  }

  setMemberRoles(
    orgID: string,
    memberID: string,
    setMemberRolesRequest: SetMemberRolesRequest,
    observe?: 'body',
    options?: RequestOptions<'json'>,
  ): Observable<MemberResponse>;
  setMemberRoles(
    orgID: string,
    memberID: string,
    setMemberRolesRequest: SetMemberRolesRequest,
    observe?: 'response',
    options?: RequestOptions<'json'>,
  ): Observable<HttpResponse<MemberResponse>>;
  setMemberRoles(
    orgID: string,
    memberID: string,
    setMemberRolesRequest: SetMemberRolesRequest,
    observe?: 'events',
    options?: RequestOptions<'json'>,
  ): Observable<HttpEvent<MemberResponse>>;
  /** Sets the roles to exactly the list given. A replace rather than an add and a remove, so two administrators editing the same person concurrently cannot merge into a set neither of them chose. Requires members.roles.assign; every role must be one the caller could grant themselves; demoting the last owner is refused with 409. */
  setMemberRoles(
    orgID: string,
    memberID: string,
    setMemberRolesRequest: SetMemberRolesRequest,
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/v1/orgs/${orgID}/members/${memberID}/roles`;

    let headers: HttpHeaders;
    if (options?.headers instanceof HttpHeaders) {
      headers = options.headers;
    } else {
      headers = new HttpHeaders(options?.headers);
    }
    // Advertise the response content type declared in the spec
    if (!headers.has('Accept')) {
      headers = headers.set('Accept', 'application/json');
    }
    // Set Content-Type for JSON requests if not already set
    if (!headers.has('Content-Type')) {
      headers = headers.set('Content-Type', 'application/json');
    }

    return this.httpClient.request('put', url, {
      body: setMemberRolesRequest,
      observe,
      headers,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    });
  }

  listRoles(
    orgID: string,
    observe?: 'body',
    options?: RequestOptions<'json'>,
  ): Observable<ListRolesOutputBody>;
  listRoles(
    orgID: string,
    observe?: 'response',
    options?: RequestOptions<'json'>,
  ): Observable<HttpResponse<ListRolesOutputBody>>;
  listRoles(
    orgID: string,
    observe?: 'events',
    options?: RequestOptions<'json'>,
  ): Observable<HttpEvent<ListRolesOutputBody>>;
  /** Every role in the organization with what it grants and how many people hold it. Requires roles.read. */
  listRoles(
    orgID: string,
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/v1/orgs/${orgID}/roles`;

    let headers: HttpHeaders;
    if (options?.headers instanceof HttpHeaders) {
      headers = options.headers;
    } else {
      headers = new HttpHeaders(options?.headers);
    }
    // Advertise the response content type declared in the spec
    if (!headers.has('Accept')) {
      headers = headers.set('Accept', 'application/json');
    }

    return this.httpClient.request('get', url, {
      observe,
      headers,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    });
  }

  createRole(
    orgID: string,
    createRoleRequest: CreateRoleRequest,
    observe?: 'body',
    options?: RequestOptions<'json'>,
  ): Observable<RoleResponse>;
  createRole(
    orgID: string,
    createRoleRequest: CreateRoleRequest,
    observe?: 'response',
    options?: RequestOptions<'json'>,
  ): Observable<HttpResponse<RoleResponse>>;
  createRole(
    orgID: string,
    createRoleRequest: CreateRoleRequest,
    observe?: 'events',
    options?: RequestOptions<'json'>,
  ): Observable<HttpEvent<RoleResponse>>;
  /** Requires roles.create. Every permission listed must be one the caller holds themselves — without that rule, roles.create would be a permission to acquire every other permission. */
  createRole(
    orgID: string,
    createRoleRequest: CreateRoleRequest,
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/v1/orgs/${orgID}/roles`;

    let headers: HttpHeaders;
    if (options?.headers instanceof HttpHeaders) {
      headers = options.headers;
    } else {
      headers = new HttpHeaders(options?.headers);
    }
    // Advertise the response content type declared in the spec
    if (!headers.has('Accept')) {
      headers = headers.set('Accept', 'application/json');
    }
    // Set Content-Type for JSON requests if not already set
    if (!headers.has('Content-Type')) {
      headers = headers.set('Content-Type', 'application/json');
    }

    return this.httpClient.request('post', url, {
      body: createRoleRequest,
      observe,
      headers,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    });
  }

  getRole(
    orgID: string,
    roleID: string,
    observe?: 'body',
    options?: RequestOptions<'json'>,
  ): Observable<RoleResponse>;
  getRole(
    orgID: string,
    roleID: string,
    observe?: 'response',
    options?: RequestOptions<'json'>,
  ): Observable<HttpResponse<RoleResponse>>;
  getRole(
    orgID: string,
    roleID: string,
    observe?: 'events',
    options?: RequestOptions<'json'>,
  ): Observable<HttpEvent<RoleResponse>>;
  /** Requires roles.read. A role id belonging to another organization is 404, not 403. */
  getRole(
    orgID: string,
    roleID: string,
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/v1/orgs/${orgID}/roles/${roleID}`;

    let headers: HttpHeaders;
    if (options?.headers instanceof HttpHeaders) {
      headers = options.headers;
    } else {
      headers = new HttpHeaders(options?.headers);
    }
    // Advertise the response content type declared in the spec
    if (!headers.has('Accept')) {
      headers = headers.set('Accept', 'application/json');
    }

    return this.httpClient.request('get', url, {
      observe,
      headers,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    });
  }

  updateRole(
    orgID: string,
    roleID: string,
    updateRoleRequest: UpdateRoleRequest,
    observe?: 'body',
    options?: RequestOptions<'json'>,
  ): Observable<RoleResponse>;
  updateRole(
    orgID: string,
    roleID: string,
    updateRoleRequest: UpdateRoleRequest,
    observe?: 'response',
    options?: RequestOptions<'json'>,
  ): Observable<HttpResponse<RoleResponse>>;
  updateRole(
    orgID: string,
    roleID: string,
    updateRoleRequest: UpdateRoleRequest,
    observe?: 'events',
    options?: RequestOptions<'json'>,
  ): Observable<HttpEvent<RoleResponse>>;
  /** Requires roles.update. Roles that ship with the product are refused with 403: every organization's copy of "admin" has to keep meaning the same thing. Clone one to get an editable version. */
  updateRole(
    orgID: string,
    roleID: string,
    updateRoleRequest: UpdateRoleRequest,
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/v1/orgs/${orgID}/roles/${roleID}`;

    let headers: HttpHeaders;
    if (options?.headers instanceof HttpHeaders) {
      headers = options.headers;
    } else {
      headers = new HttpHeaders(options?.headers);
    }
    // Advertise the response content type declared in the spec
    if (!headers.has('Accept')) {
      headers = headers.set('Accept', 'application/json');
    }
    // Set Content-Type for JSON requests if not already set
    if (!headers.has('Content-Type')) {
      headers = headers.set('Content-Type', 'application/json');
    }

    return this.httpClient.request('patch', url, {
      body: updateRoleRequest,
      observe,
      headers,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    });
  }

  deleteRole(
    orgID: string,
    roleID: string,
    observe?: 'body',
    options?: RequestOptions<'json'>,
  ): Observable<any>;
  deleteRole(
    orgID: string,
    roleID: string,
    observe?: 'response',
    options?: RequestOptions<'json'>,
  ): Observable<HttpResponse<any>>;
  deleteRole(
    orgID: string,
    roleID: string,
    observe?: 'events',
    options?: RequestOptions<'json'>,
  ): Observable<HttpEvent<any>>;
  /** Requires roles.delete. Refused with 409 while anyone still holds it: deleting it anyway would take permissions away from people the caller never looked at, and leave nothing behind to explain why. */
  deleteRole(
    orgID: string,
    roleID: string,
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/v1/orgs/${orgID}/roles/${roleID}`;

    let headers: HttpHeaders;
    if (options?.headers instanceof HttpHeaders) {
      headers = options.headers;
    } else {
      headers = new HttpHeaders(options?.headers);
    }

    return this.httpClient.request('delete', url, {
      observe,
      headers,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    });
  }

  setRolePermissions(
    orgID: string,
    roleID: string,
    setRolePermissionsRequest: SetRolePermissionsRequest,
    observe?: 'body',
    options?: RequestOptions<'json'>,
  ): Observable<RoleResponse>;
  setRolePermissions(
    orgID: string,
    roleID: string,
    setRolePermissionsRequest: SetRolePermissionsRequest,
    observe?: 'response',
    options?: RequestOptions<'json'>,
  ): Observable<HttpResponse<RoleResponse>>;
  setRolePermissions(
    orgID: string,
    roleID: string,
    setRolePermissionsRequest: SetRolePermissionsRequest,
    observe?: 'events',
    options?: RequestOptions<'json'>,
  ): Observable<HttpEvent<RoleResponse>>;
  /** Sets the permissions to exactly the list given. Requires roles.update, refuses roles that ship with the product, and refuses any permission the caller does not hold themselves. */
  setRolePermissions(
    orgID: string,
    roleID: string,
    setRolePermissionsRequest: SetRolePermissionsRequest,
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/v1/orgs/${orgID}/roles/${roleID}/permissions`;

    let headers: HttpHeaders;
    if (options?.headers instanceof HttpHeaders) {
      headers = options.headers;
    } else {
      headers = new HttpHeaders(options?.headers);
    }
    // Advertise the response content type declared in the spec
    if (!headers.has('Accept')) {
      headers = headers.set('Accept', 'application/json');
    }
    // Set Content-Type for JSON requests if not already set
    if (!headers.has('Content-Type')) {
      headers = headers.set('Content-Type', 'application/json');
    }

    return this.httpClient.request('put', url, {
      body: setRolePermissionsRequest,
      observe,
      headers,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    });
  }

  listPermissionCatalog(
    observe?: 'body',
    options?: RequestOptions<'json'>,
  ): Observable<ListPermissionsOutputBody>;
  listPermissionCatalog(
    observe?: 'response',
    options?: RequestOptions<'json'>,
  ): Observable<HttpResponse<ListPermissionsOutputBody>>;
  listPermissionCatalog(
    observe?: 'events',
    options?: RequestOptions<'json'>,
  ): Observable<HttpEvent<ListPermissionsOutputBody>>;
  /** The catalog the role editor is built from. Self-service: it describes the product rather than any organization's data, and a caller who cannot see it cannot be shown a meaningful role editor. */
  listPermissionCatalog(
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/v1/permissions`;

    let headers: HttpHeaders;
    if (options?.headers instanceof HttpHeaders) {
      headers = options.headers;
    } else {
      headers = new HttpHeaders(options?.headers);
    }
    // Advertise the response content type declared in the spec
    if (!headers.has('Accept')) {
      headers = headers.set('Accept', 'application/json');
    }

    return this.httpClient.request('get', url, {
      observe,
      headers,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    });
  }
}
