// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
 * Generated by ng-openapi
 * Generated Angular service for Platform controller
 * Do not edit this file manually
 */
import {
  HttpClient,
  HttpContext,
  HttpContextToken,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse,
} from '@angular/common/http';
import { inject, Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from '../tokens';
import { HttpParamsBuilder } from '../utils/http-params-builder';
import {
  RequestOptions,
  ListAuditOutputBody,
  ListPlatformOrganizationsOutputBody,
  CreatePlatformOrganizationRequest,
  PlatformOrganizationResponse,
  ListPlatformUsersOutputBody,
  SuspendPlatformUserRequest,
} from '../models';

@Injectable({ providedIn: 'root' })
export class PlatformService {
  private readonly httpClient: HttpClient = inject(HttpClient);
  private readonly basePath: string = inject(BASE_PATH_DEFAULT);
  private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

  private createContextWithClientId(existingContext?: HttpContext): HttpContext {
    const context = existingContext || new HttpContext();
    return context.set(this.clientContextToken, 'default');
  }

  listPlatformAuditEvents(
    limit?: number,
    offset?: number,
    observe?: 'body',
    options?: RequestOptions<'json'>,
  ): Observable<ListAuditOutputBody>;
  listPlatformAuditEvents(
    limit?: number,
    offset?: number,
    observe?: 'response',
    options?: RequestOptions<'json'>,
  ): Observable<HttpResponse<ListAuditOutputBody>>;
  listPlatformAuditEvents(
    limit?: number,
    offset?: number,
    observe?: 'events',
    options?: RequestOptions<'json'>,
  ): Observable<HttpEvent<ListAuditOutputBody>>;
  /** The same log across every organization, plus the changes that belong to no organization. Requires platform.audit.read. */
  listPlatformAuditEvents(
    limit?: number,
    offset?: number,
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/v1/platform/audit`;

    let params = new HttpParams();
    if (limit != null) {
      params = HttpParamsBuilder.addToHttpParams(params, limit, 'limit');
    }
    if (offset != null) {
      params = HttpParamsBuilder.addToHttpParams(params, offset, 'offset');
    }

    let headers: HttpHeaders;
    if (options?.headers instanceof HttpHeaders) {
      headers = options.headers;
    } else {
      headers = new HttpHeaders(options?.headers);
    }
    // Advertise the response content type declared in the spec
    if (!headers.has('Accept')) {
      headers = headers.set('Accept', 'application/json');
    }

    return this.httpClient.request('get', url, {
      observe,
      headers,
      params,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    });
  }

  listPlatformOrganizations(
    limit?: number,
    offset?: number,
    observe?: 'body',
    options?: RequestOptions<'json'>,
  ): Observable<ListPlatformOrganizationsOutputBody>;
  listPlatformOrganizations(
    limit?: number,
    offset?: number,
    observe?: 'response',
    options?: RequestOptions<'json'>,
  ): Observable<HttpResponse<ListPlatformOrganizationsOutputBody>>;
  listPlatformOrganizations(
    limit?: number,
    offset?: number,
    observe?: 'events',
    options?: RequestOptions<'json'>,
  ): Observable<HttpEvent<ListPlatformOrganizationsOutputBody>>;
  /** Requires platform.organizations.read. The only listing that crosses tenants, which is why it is measured against the installation rather than any one organization. */
  listPlatformOrganizations(
    limit?: number,
    offset?: number,
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/v1/platform/organizations`;

    let params = new HttpParams();
    if (limit != null) {
      params = HttpParamsBuilder.addToHttpParams(params, limit, 'limit');
    }
    if (offset != null) {
      params = HttpParamsBuilder.addToHttpParams(params, offset, 'offset');
    }

    let headers: HttpHeaders;
    if (options?.headers instanceof HttpHeaders) {
      headers = options.headers;
    } else {
      headers = new HttpHeaders(options?.headers);
    }
    // Advertise the response content type declared in the spec
    if (!headers.has('Accept')) {
      headers = headers.set('Accept', 'application/json');
    }

    return this.httpClient.request('get', url, {
      observe,
      headers,
      params,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    });
  }

  createPlatformOrganization(
    createPlatformOrganizationRequest: CreatePlatformOrganizationRequest,
    observe?: 'body',
    options?: RequestOptions<'json'>,
  ): Observable<PlatformOrganizationResponse>;
  createPlatformOrganization(
    createPlatformOrganizationRequest: CreatePlatformOrganizationRequest,
    observe?: 'response',
    options?: RequestOptions<'json'>,
  ): Observable<HttpResponse<PlatformOrganizationResponse>>;
  createPlatformOrganization(
    createPlatformOrganizationRequest: CreatePlatformOrganizationRequest,
    observe?: 'events',
    options?: RequestOptions<'json'>,
  ): Observable<HttpEvent<PlatformOrganizationResponse>>;
  /** Requires platform.organizations.create. The organization is created with the roles that ship with the product, and with nobody in it — the creator is not silently made an owner, because that is a separate and visible act. */
  createPlatformOrganization(
    createPlatformOrganizationRequest: CreatePlatformOrganizationRequest,
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/v1/platform/organizations`;

    let headers: HttpHeaders;
    if (options?.headers instanceof HttpHeaders) {
      headers = options.headers;
    } else {
      headers = new HttpHeaders(options?.headers);
    }
    // Advertise the response content type declared in the spec
    if (!headers.has('Accept')) {
      headers = headers.set('Accept', 'application/json');
    }
    // Set Content-Type for JSON requests if not already set
    if (!headers.has('Content-Type')) {
      headers = headers.set('Content-Type', 'application/json');
    }

    return this.httpClient.request('post', url, {
      body: createPlatformOrganizationRequest,
      observe,
      headers,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    });
  }

  deletePlatformOrganization(
    id: string,
    observe?: 'body',
    options?: RequestOptions<'json'>,
  ): Observable<any>;
  deletePlatformOrganization(
    id: string,
    observe?: 'response',
    options?: RequestOptions<'json'>,
  ): Observable<HttpResponse<any>>;
  deletePlatformOrganization(
    id: string,
    observe?: 'events',
    options?: RequestOptions<'json'>,
  ): Observable<HttpEvent<any>>;
  /** Requires platform.organizations.delete. The default organization is protected and is refused with 409. */
  deletePlatformOrganization(
    id: string,
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/v1/platform/organizations/${id}`;

    let headers: HttpHeaders;
    if (options?.headers instanceof HttpHeaders) {
      headers = options.headers;
    } else {
      headers = new HttpHeaders(options?.headers);
    }

    return this.httpClient.request('delete', url, {
      observe,
      headers,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    });
  }

  listPlatformUsers(
    limit?: number,
    offset?: number,
    observe?: 'body',
    options?: RequestOptions<'json'>,
  ): Observable<ListPlatformUsersOutputBody>;
  listPlatformUsers(
    limit?: number,
    offset?: number,
    observe?: 'response',
    options?: RequestOptions<'json'>,
  ): Observable<HttpResponse<ListPlatformUsersOutputBody>>;
  listPlatformUsers(
    limit?: number,
    offset?: number,
    observe?: 'events',
    options?: RequestOptions<'json'>,
  ): Observable<HttpEvent<ListPlatformUsersOutputBody>>;
  /** Requires platform.users.read. */
  listPlatformUsers(
    limit?: number,
    offset?: number,
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/v1/platform/users`;

    let params = new HttpParams();
    if (limit != null) {
      params = HttpParamsBuilder.addToHttpParams(params, limit, 'limit');
    }
    if (offset != null) {
      params = HttpParamsBuilder.addToHttpParams(params, offset, 'offset');
    }

    let headers: HttpHeaders;
    if (options?.headers instanceof HttpHeaders) {
      headers = options.headers;
    } else {
      headers = new HttpHeaders(options?.headers);
    }
    // Advertise the response content type declared in the spec
    if (!headers.has('Accept')) {
      headers = headers.set('Accept', 'application/json');
    }

    return this.httpClient.request('get', url, {
      observe,
      headers,
      params,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    });
  }

  suspendPlatformUser(
    id: string,
    suspendPlatformUserRequest: SuspendPlatformUserRequest,
    observe?: 'body',
    options?: RequestOptions<'json'>,
  ): Observable<any>;
  suspendPlatformUser(
    id: string,
    suspendPlatformUserRequest: SuspendPlatformUserRequest,
    observe?: 'response',
    options?: RequestOptions<'json'>,
  ): Observable<HttpResponse<any>>;
  suspendPlatformUser(
    id: string,
    suspendPlatformUserRequest: SuspendPlatformUserRequest,
    observe?: 'events',
    options?: RequestOptions<'json'>,
  ): Observable<HttpEvent<any>>;
  /** Requires platform.users.suspend. Suspending takes effect on tokens already issued, on the next request rather than at expiry — the same promise device revocation makes. Memberships and roles are kept, so restoring gives back exactly what was there. */
  suspendPlatformUser(
    id: string,
    suspendPlatformUserRequest: SuspendPlatformUserRequest,
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/v1/platform/users/${id}`;

    let headers: HttpHeaders;
    if (options?.headers instanceof HttpHeaders) {
      headers = options.headers;
    } else {
      headers = new HttpHeaders(options?.headers);
    }
    // Set Content-Type for JSON requests if not already set
    if (!headers.has('Content-Type')) {
      headers = headers.set('Content-Type', 'application/json');
    }

    return this.httpClient.request('patch', url, {
      body: suspendPlatformUserRequest,
      observe,
      headers,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    });
  }

  deletePlatformUser(
    id: string,
    observe?: 'body',
    options?: RequestOptions<'json'>,
  ): Observable<any>;
  deletePlatformUser(
    id: string,
    observe?: 'response',
    options?: RequestOptions<'json'>,
  ): Observable<HttpResponse<any>>;
  deletePlatformUser(
    id: string,
    observe?: 'events',
    options?: RequestOptions<'json'>,
  ): Observable<HttpEvent<any>>;
  /** Requires platform.users.delete. A soft delete: the account stops working everywhere and its devices are revoked, but the row survives so login history and audit records keep making sense. */
  deletePlatformUser(
    id: string,
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/v1/platform/users/${id}`;

    let headers: HttpHeaders;
    if (options?.headers instanceof HttpHeaders) {
      headers = options.headers;
    } else {
      headers = new HttpHeaders(options?.headers);
    }

    return this.httpClient.request('delete', url, {
      observe,
      headers,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    });
  }
}
