// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
 * Generated by ng-openapi
 * Generated Angular service for Users controller
 * Do not edit this file manually
 */
import {
  HttpClient,
  HttpContext,
  HttpContextToken,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse,
} from '@angular/common/http';
import { inject, Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from '../tokens';
import { HttpParamsBuilder } from '../utils/http-params-builder';
import { RequestOptions, UserResponse } from '../models';

@Injectable({ providedIn: 'root' })
export class UsersService {
  private readonly httpClient: HttpClient = inject(HttpClient);
  private readonly basePath: string = inject(BASE_PATH_DEFAULT);
  private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

  private createContextWithClientId(existingContext?: HttpContext): HttpContext {
    const context = existingContext || new HttpContext();
    return context.set(this.clientContextToken, 'default');
  }

  getMe(observe?: 'body', options?: RequestOptions<'json'>): Observable<UserResponse>;
  getMe(
    observe?: 'response',
    options?: RequestOptions<'json'>,
  ): Observable<HttpResponse<UserResponse>>;
  getMe(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<UserResponse>>;
  /** Returns the account that owns the Bearer token. */
  getMe(
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/v1/me`;

    let headers: HttpHeaders;
    if (options?.headers instanceof HttpHeaders) {
      headers = options.headers;
    } else {
      headers = new HttpHeaders(options?.headers);
    }
    // Advertise the response content type declared in the spec
    if (!headers.has('Accept')) {
      headers = headers.set('Accept', 'application/json');
    }

    return this.httpClient.request('get', url, {
      observe,
      headers,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    });
  }

  getUser(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<UserResponse>;
  getUser(
    id: string,
    observe?: 'response',
    options?: RequestOptions<'json'>,
  ): Observable<HttpResponse<UserResponse>>;
  getUser(
    id: string,
    observe?: 'events',
    options?: RequestOptions<'json'>,
  ): Observable<HttpEvent<UserResponse>>;
  /** Returns the authenticated user's own record. Another user's id is indistinguishable from a missing one. */
  getUser(
    id: string,
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/v1/users/${id}`;

    let headers: HttpHeaders;
    if (options?.headers instanceof HttpHeaders) {
      headers = options.headers;
    } else {
      headers = new HttpHeaders(options?.headers);
    }
    // Advertise the response content type declared in the spec
    if (!headers.has('Accept')) {
      headers = headers.set('Accept', 'application/json');
    }

    return this.httpClient.request('get', url, {
      observe,
      headers,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    });
  }
}
